apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://building-os.prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 15s

  - name: Loki
    type: loki
    uid: loki
    url: http://building-os.loki:3100

  - name: Tempo
    type: tempo
    uid: tempo
    url: http://building-os.tempo:3200
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
      lokiSearch:
        datasourceUid: loki
      serviceMap:
        datasourceUid: prometheus
