//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Text.Json;
using Corvus.Json;
using Corvus.Json.Internal;

namespace BuildingOS.Shared.Entities;
public readonly partial struct BacnetDeviceMessageJson
{
    /// <summary>
    /// A type generated from a JsonSchema specification.
    /// </summary>
    public readonly partial struct ItemsEntity
    {
        /// <summary>
        /// The well-known property names in the JSON object.
        /// </summary>
        public static class JsonPropertyNames
        {
            /// <summary>
            /// JSON property name for <see cref = "DeviceId"/>.
            /// </summary>
            public static ReadOnlySpan<byte> DeviceIdUtf8 => "Device_id"u8;

            /// <summary>
            /// JSON property name for <see cref = "DeviceId"/>.
            /// </summary>
            public const string DeviceId = "Device_id";
            /// <summary>
            /// JSON property name for <see cref = "ValueString"/>.
            /// </summary>
            public static ReadOnlySpan<byte> ValueStringUtf8 => "ValueString"u8;

            /// <summary>
            /// JSON property name for <see cref = "ValueString"/>.
            /// </summary>
            public const string ValueString = "ValueString";
        }

        /// <summary>
        /// Gets DeviceId.
        /// </summary>
        public Corvus.Json.JsonString DeviceId
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.DeviceIdUtf8, out JsonElement result))
                    {
                        return new Corvus.Json.JsonString(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.DeviceId, out JsonAny result))
                    {
                        return result.As<Corvus.Json.JsonString>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets ValueString.
        /// </summary>
        public BuildingOS.Shared.Entities.BacnetDeviceMessageJson.ItemsEntity.ValueStringEntityArray ValueString
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.ValueStringUtf8, out JsonElement result))
                    {
                        return new BuildingOS.Shared.Entities.BacnetDeviceMessageJson.ItemsEntity.ValueStringEntityArray(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.ValueString, out JsonAny result))
                    {
                        return result.As<BuildingOS.Shared.Entities.BacnetDeviceMessageJson.ItemsEntity.ValueStringEntityArray>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Creates an instance of a <see cref = "ItemsEntity"/>.
        /// </summary>
        public static ItemsEntity Create(Corvus.Json.JsonString deviceId, BuildingOS.Shared.Entities.BacnetDeviceMessageJson.ItemsEntity.ValueStringEntityArray valueString)
        {
            var builder = ImmutableList.CreateBuilder<JsonObjectProperty>();
            builder.Add(JsonPropertyNames.DeviceId, deviceId.AsAny);
            builder.Add(JsonPropertyNames.ValueString, valueString.AsAny);
            return new(builder.ToImmutable());
        }

        /// <summary>
        /// Sets Device_id.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public ItemsEntity WithDeviceId(in Corvus.Json.JsonString value)
        {
            return this.SetProperty(JsonPropertyNames.DeviceId, value);
        }

        /// <summary>
        /// Sets ValueString.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public ItemsEntity WithValueString(in BuildingOS.Shared.Entities.BacnetDeviceMessageJson.ItemsEntity.ValueStringEntityArray value)
        {
            return this.SetProperty(JsonPropertyNames.ValueString, value);
        }

        private static ValidationContext __CorvusValidateDeviceId(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Corvus.Json.JsonString>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateValueString(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<BuildingOS.Shared.Entities.BacnetDeviceMessageJson.ItemsEntity.ValueStringEntityArray>().Validate(validationContext, level);
        }

        /// <summary>
        /// Tries to get the validator for the given property.
        /// </summary>
        /// <param name = "property">The property for which to get the validator.</param>
        /// <param name = "hasJsonElementBacking"><c>True</c> if the object containing the property has a JsonElement backing.</param>
        /// <param name = "propertyValidator">The validator for the property, if provided by this schema.</param>
        /// <returns><c>True</c> if the validator was found.</returns>
        private bool __TryGetCorvusLocalPropertiesValidator(in JsonObjectProperty property, bool hasJsonElementBacking, [NotNullWhen(true)] out ObjectPropertyValidator? propertyValidator)
        {
            if (hasJsonElementBacking)
            {
                if (property.NameEquals(JsonPropertyNames.DeviceIdUtf8))
                {
                    propertyValidator = __CorvusValidateDeviceId;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.ValueStringUtf8))
                {
                    propertyValidator = __CorvusValidateValueString;
                    return true;
                }
            }
            else
            {
                if (property.NameEquals(JsonPropertyNames.DeviceId))
                {
                    propertyValidator = __CorvusValidateDeviceId;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.ValueString))
                {
                    propertyValidator = __CorvusValidateValueString;
                    return true;
                }
            }

            propertyValidator = null;
            return false;
        }
    }
}