//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Text.Json;
using Corvus.Json;
using Corvus.Json.Internal;

namespace BuildingOS.Shared.Entities;
public readonly partial struct BacnetDeviceMessageJson
{
    public readonly partial struct ItemsEntity
    {
        public readonly partial struct ValueStringEntityArray
        {
            /// <summary>
            /// A type generated from a JsonSchema specification.
            /// </summary>
            public readonly partial struct ValueStringEntity
            {
                /// <summary>
                /// The well-known property names in the JSON object.
                /// </summary>
                public static class JsonPropertyNames
                {
                    /// <summary>
                    /// JSON property name for <see cref = "BAnetDevice"/>.
                    /// </summary>
                    public static ReadOnlySpan<byte> BAnetDeviceUtf8 => "BACnetDevice"u8;

                    /// <summary>
                    /// JSON property name for <see cref = "BAnetDevice"/>.
                    /// </summary>
                    public const string BAnetDevice = "BACnetDevice";
                    /// <summary>
                    /// JSON property name for <see cref = "BAnetObject"/>.
                    /// </summary>
                    public static ReadOnlySpan<byte> BAnetObjectUtf8 => "BACnetObject"u8;

                    /// <summary>
                    /// JSON property name for <see cref = "BAnetObject"/>.
                    /// </summary>
                    public const string BAnetObject = "BACnetObject";
                    /// <summary>
                    /// JSON property name for <see cref = "Properties"/>.
                    /// </summary>
                    public static ReadOnlySpan<byte> PropertiesUtf8 => "Properties"u8;

                    /// <summary>
                    /// JSON property name for <see cref = "Properties"/>.
                    /// </summary>
                    public const string Properties = "Properties";
                    /// <summary>
                    /// JSON property name for <see cref = "TimeStamp"/>.
                    /// </summary>
                    public static ReadOnlySpan<byte> TimeStampUtf8 => "TimeStamp"u8;

                    /// <summary>
                    /// JSON property name for <see cref = "TimeStamp"/>.
                    /// </summary>
                    public const string TimeStamp = "TimeStamp";
                }

                /// <summary>
                /// Gets BAnetDevice.
                /// </summary>
                public Corvus.Json.JsonInteger BAnetDevice
                {
                    get
                    {
                        if ((this.backing & Backing.JsonElement) != 0)
                        {
                            if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                            {
                                return default;
                            }

                            if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.BAnetDeviceUtf8, out JsonElement result))
                            {
                                return new Corvus.Json.JsonInteger(result);
                            }
                        }

                        if ((this.backing & Backing.Object) != 0)
                        {
                            if (this.objectBacking.TryGetValue(JsonPropertyNames.BAnetDevice, out JsonAny result))
                            {
                                return result.As<Corvus.Json.JsonInteger>();
                            }
                        }

                        return default;
                    }
                }

                /// <summary>
                /// Gets BAnetObject.
                /// </summary>
                public BuildingOS.Shared.Entities.BacnetDeviceMessageJson.ItemsEntity.ValueStringEntityArray.ValueStringEntity.BAnetObjectEntity BAnetObject
                {
                    get
                    {
                        if ((this.backing & Backing.JsonElement) != 0)
                        {
                            if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                            {
                                return default;
                            }

                            if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.BAnetObjectUtf8, out JsonElement result))
                            {
                                return new BuildingOS.Shared.Entities.BacnetDeviceMessageJson.ItemsEntity.ValueStringEntityArray.ValueStringEntity.BAnetObjectEntity(result);
                            }
                        }

                        if ((this.backing & Backing.Object) != 0)
                        {
                            if (this.objectBacking.TryGetValue(JsonPropertyNames.BAnetObject, out JsonAny result))
                            {
                                return result.As<BuildingOS.Shared.Entities.BacnetDeviceMessageJson.ItemsEntity.ValueStringEntityArray.ValueStringEntity.BAnetObjectEntity>();
                            }
                        }

                        return default;
                    }
                }

                /// <summary>
                /// Gets Properties.
                /// </summary>
                public BuildingOS.Shared.Entities.BacnetDeviceMessageJson.ItemsEntity.ValueStringEntityArray.ValueStringEntity.PropertiesEntity Properties
                {
                    get
                    {
                        if ((this.backing & Backing.JsonElement) != 0)
                        {
                            if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                            {
                                return default;
                            }

                            if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.PropertiesUtf8, out JsonElement result))
                            {
                                return new BuildingOS.Shared.Entities.BacnetDeviceMessageJson.ItemsEntity.ValueStringEntityArray.ValueStringEntity.PropertiesEntity(result);
                            }
                        }

                        if ((this.backing & Backing.Object) != 0)
                        {
                            if (this.objectBacking.TryGetValue(JsonPropertyNames.Properties, out JsonAny result))
                            {
                                return result.As<BuildingOS.Shared.Entities.BacnetDeviceMessageJson.ItemsEntity.ValueStringEntityArray.ValueStringEntity.PropertiesEntity>();
                            }
                        }

                        return default;
                    }
                }

                /// <summary>
                /// Gets TimeStamp.
                /// </summary>
                public Corvus.Json.JsonDateTime TimeStamp
                {
                    get
                    {
                        if ((this.backing & Backing.JsonElement) != 0)
                        {
                            if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                            {
                                return default;
                            }

                            if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.TimeStampUtf8, out JsonElement result))
                            {
                                return new Corvus.Json.JsonDateTime(result);
                            }
                        }

                        if ((this.backing & Backing.Object) != 0)
                        {
                            if (this.objectBacking.TryGetValue(JsonPropertyNames.TimeStamp, out JsonAny result))
                            {
                                return result.As<Corvus.Json.JsonDateTime>();
                            }
                        }

                        return default;
                    }
                }

                /// <summary>
                /// Creates an instance of a <see cref = "ValueStringEntity"/>.
                /// </summary>
                public static ValueStringEntity Create(Corvus.Json.JsonInteger bAnetDevice, BuildingOS.Shared.Entities.BacnetDeviceMessageJson.ItemsEntity.ValueStringEntityArray.ValueStringEntity.BAnetObjectEntity bAnetObject, BuildingOS.Shared.Entities.BacnetDeviceMessageJson.ItemsEntity.ValueStringEntityArray.ValueStringEntity.PropertiesEntity properties, Corvus.Json.JsonDateTime timeStamp)
                {
                    var builder = ImmutableList.CreateBuilder<JsonObjectProperty>();
                    builder.Add(JsonPropertyNames.BAnetDevice, bAnetDevice.AsAny);
                    builder.Add(JsonPropertyNames.BAnetObject, bAnetObject.AsAny);
                    builder.Add(JsonPropertyNames.Properties, properties.AsAny);
                    builder.Add(JsonPropertyNames.TimeStamp, timeStamp.AsAny);
                    return new(builder.ToImmutable());
                }

                /// <summary>
                /// Sets BACnetDevice.
                /// </summary>
                /// <param name = "value">The value to set.</param>
                /// <returns>The entity with the updated property.</returns>
                public ValueStringEntity WithBAnetDevice(in Corvus.Json.JsonInteger value)
                {
                    return this.SetProperty(JsonPropertyNames.BAnetDevice, value);
                }

                /// <summary>
                /// Sets BACnetObject.
                /// </summary>
                /// <param name = "value">The value to set.</param>
                /// <returns>The entity with the updated property.</returns>
                public ValueStringEntity WithBAnetObject(in BuildingOS.Shared.Entities.BacnetDeviceMessageJson.ItemsEntity.ValueStringEntityArray.ValueStringEntity.BAnetObjectEntity value)
                {
                    return this.SetProperty(JsonPropertyNames.BAnetObject, value);
                }

                /// <summary>
                /// Sets Properties.
                /// </summary>
                /// <param name = "value">The value to set.</param>
                /// <returns>The entity with the updated property.</returns>
                public ValueStringEntity WithProperties(in BuildingOS.Shared.Entities.BacnetDeviceMessageJson.ItemsEntity.ValueStringEntityArray.ValueStringEntity.PropertiesEntity value)
                {
                    return this.SetProperty(JsonPropertyNames.Properties, value);
                }

                /// <summary>
                /// Sets TimeStamp.
                /// </summary>
                /// <param name = "value">The value to set.</param>
                /// <returns>The entity with the updated property.</returns>
                public ValueStringEntity WithTimeStamp(in Corvus.Json.JsonDateTime value)
                {
                    return this.SetProperty(JsonPropertyNames.TimeStamp, value);
                }

                private static ValidationContext __CorvusValidateTimeStamp(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
                {
                    return property.ValueAs<Corvus.Json.JsonDateTime>().Validate(validationContext, level);
                }

                private static ValidationContext __CorvusValidateBAnetDevice(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
                {
                    return property.ValueAs<Corvus.Json.JsonInteger>().Validate(validationContext, level);
                }

                private static ValidationContext __CorvusValidateBAnetObject(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
                {
                    return property.ValueAs<BuildingOS.Shared.Entities.BacnetDeviceMessageJson.ItemsEntity.ValueStringEntityArray.ValueStringEntity.BAnetObjectEntity>().Validate(validationContext, level);
                }

                private static ValidationContext __CorvusValidateProperties(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
                {
                    return property.ValueAs<BuildingOS.Shared.Entities.BacnetDeviceMessageJson.ItemsEntity.ValueStringEntityArray.ValueStringEntity.PropertiesEntity>().Validate(validationContext, level);
                }

                /// <summary>
                /// Tries to get the validator for the given property.
                /// </summary>
                /// <param name = "property">The property for which to get the validator.</param>
                /// <param name = "hasJsonElementBacking"><c>True</c> if the object containing the property has a JsonElement backing.</param>
                /// <param name = "propertyValidator">The validator for the property, if provided by this schema.</param>
                /// <returns><c>True</c> if the validator was found.</returns>
                private bool __TryGetCorvusLocalPropertiesValidator(in JsonObjectProperty property, bool hasJsonElementBacking, [NotNullWhen(true)] out ObjectPropertyValidator? propertyValidator)
                {
                    if (hasJsonElementBacking)
                    {
                        if (property.NameEquals(JsonPropertyNames.TimeStampUtf8))
                        {
                            propertyValidator = __CorvusValidateTimeStamp;
                            return true;
                        }
                        else if (property.NameEquals(JsonPropertyNames.BAnetDeviceUtf8))
                        {
                            propertyValidator = __CorvusValidateBAnetDevice;
                            return true;
                        }
                        else if (property.NameEquals(JsonPropertyNames.BAnetObjectUtf8))
                        {
                            propertyValidator = __CorvusValidateBAnetObject;
                            return true;
                        }
                        else if (property.NameEquals(JsonPropertyNames.PropertiesUtf8))
                        {
                            propertyValidator = __CorvusValidateProperties;
                            return true;
                        }
                    }
                    else
                    {
                        if (property.NameEquals(JsonPropertyNames.TimeStamp))
                        {
                            propertyValidator = __CorvusValidateTimeStamp;
                            return true;
                        }
                        else if (property.NameEquals(JsonPropertyNames.BAnetDevice))
                        {
                            propertyValidator = __CorvusValidateBAnetDevice;
                            return true;
                        }
                        else if (property.NameEquals(JsonPropertyNames.BAnetObject))
                        {
                            propertyValidator = __CorvusValidateBAnetObject;
                            return true;
                        }
                        else if (property.NameEquals(JsonPropertyNames.Properties))
                        {
                            propertyValidator = __CorvusValidateProperties;
                            return true;
                        }
                    }

                    propertyValidator = null;
                    return false;
                }
            }
        }
    }
}