//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Text.Json;
using Corvus.Json;
using Corvus.Json.Internal;

namespace BuildingOS.Shared.Entities;
public readonly partial struct BacnetDeviceMessageJson
{
    public readonly partial struct ItemsEntity
    {
        public readonly partial struct ValueStringEntityArray
        {
            public readonly partial struct ValueStringEntity
            {
                /// <summary>
                /// A type generated from a JsonSchema specification.
                /// </summary>
                public readonly partial struct PropertiesEntity
                {
                    /// <summary>
                    /// The well-known property names in the JSON object.
                    /// </summary>
                    public static class JsonPropertyNames
                    {
                        /// <summary>
                        /// JSON property name for <see cref = "PresentValue"/>.
                        /// </summary>
                        public static ReadOnlySpan<byte> PresentValueUtf8 => "PresentValue"u8;

                        /// <summary>
                        /// JSON property name for <see cref = "PresentValue"/>.
                        /// </summary>
                        public const string PresentValue = "PresentValue";
                    }

                    /// <summary>
                    /// Gets PresentValue.
                    /// </summary>
                    public Corvus.Json.JsonNumber PresentValue
                    {
                        get
                        {
                            if ((this.backing & Backing.JsonElement) != 0)
                            {
                                if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                                {
                                    return default;
                                }

                                if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.PresentValueUtf8, out JsonElement result))
                                {
                                    return new Corvus.Json.JsonNumber(result);
                                }
                            }

                            if ((this.backing & Backing.Object) != 0)
                            {
                                if (this.objectBacking.TryGetValue(JsonPropertyNames.PresentValue, out JsonAny result))
                                {
                                    return result.As<Corvus.Json.JsonNumber>();
                                }
                            }

                            return default;
                        }
                    }

                    /// <summary>
                    /// Creates an instance of a <see cref = "PropertiesEntity"/>.
                    /// </summary>
                    public static PropertiesEntity Create(Corvus.Json.JsonNumber presentValue)
                    {
                        var builder = ImmutableList.CreateBuilder<JsonObjectProperty>();
                        builder.Add(JsonPropertyNames.PresentValue, presentValue.AsAny);
                        return new(builder.ToImmutable());
                    }

                    /// <summary>
                    /// Sets PresentValue.
                    /// </summary>
                    /// <param name = "value">The value to set.</param>
                    /// <returns>The entity with the updated property.</returns>
                    public PropertiesEntity WithPresentValue(in Corvus.Json.JsonNumber value)
                    {
                        return this.SetProperty(JsonPropertyNames.PresentValue, value);
                    }

                    private static ValidationContext __CorvusValidatePresentValue(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
                    {
                        return property.ValueAs<Corvus.Json.JsonNumber>().Validate(validationContext, level);
                    }

                    /// <summary>
                    /// Tries to get the validator for the given property.
                    /// </summary>
                    /// <param name = "property">The property for which to get the validator.</param>
                    /// <param name = "hasJsonElementBacking"><c>True</c> if the object containing the property has a JsonElement backing.</param>
                    /// <param name = "propertyValidator">The validator for the property, if provided by this schema.</param>
                    /// <returns><c>True</c> if the validator was found.</returns>
                    private bool __TryGetCorvusLocalPropertiesValidator(in JsonObjectProperty property, bool hasJsonElementBacking, [NotNullWhen(true)] out ObjectPropertyValidator? propertyValidator)
                    {
                        if (hasJsonElementBacking)
                        {
                            if (property.NameEquals(JsonPropertyNames.PresentValueUtf8))
                            {
                                propertyValidator = __CorvusValidatePresentValue;
                                return true;
                            }
                        }
                        else
                        {
                            if (property.NameEquals(JsonPropertyNames.PresentValue))
                            {
                                propertyValidator = __CorvusValidatePresentValue;
                                return true;
                            }
                        }

                        propertyValidator = null;
                        return false;
                    }
                }
            }
        }
    }
}