//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Text.Json;
using Corvus.Json;
using Corvus.Json.Internal;

namespace BuildingOS.Shared.Entities;
public readonly partial struct BacnetDeviceMessageJson
{
    public readonly partial struct ItemsEntity
    {
        public readonly partial struct ValueStringEntityArray
        {
            public readonly partial struct ValueStringEntity
            {
                public readonly partial struct BAnetObjectEntity
                {
                    /// <summary>
                    /// A type generated from a JsonSchema specification.
                    /// </summary>
                    public readonly partial struct ValueEntity
                    {
                        /// <summary>
                        /// The well-known property names in the JSON object.
                        /// </summary>
                        public static class JsonPropertyNames
                        {
                            /// <summary>
                            /// JSON property name for <see cref = "InstanceNo"/>.
                            /// </summary>
                            public static ReadOnlySpan<byte> InstanceNoUtf8 => "InstanceNo"u8;

                            /// <summary>
                            /// JSON property name for <see cref = "InstanceNo"/>.
                            /// </summary>
                            public const string InstanceNo = "InstanceNo";
                            /// <summary>
                            /// JSON property name for <see cref = "ObjectType"/>.
                            /// </summary>
                            public static ReadOnlySpan<byte> ObjectTypeUtf8 => "ObjectType"u8;

                            /// <summary>
                            /// JSON property name for <see cref = "ObjectType"/>.
                            /// </summary>
                            public const string ObjectType = "ObjectType";
                        }

                        /// <summary>
                        /// Gets InstanceNo.
                        /// </summary>
                        public Corvus.Json.JsonInteger InstanceNo
                        {
                            get
                            {
                                if ((this.backing & Backing.JsonElement) != 0)
                                {
                                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                                    {
                                        return default;
                                    }

                                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.InstanceNoUtf8, out JsonElement result))
                                    {
                                        return new Corvus.Json.JsonInteger(result);
                                    }
                                }

                                if ((this.backing & Backing.Object) != 0)
                                {
                                    if (this.objectBacking.TryGetValue(JsonPropertyNames.InstanceNo, out JsonAny result))
                                    {
                                        return result.As<Corvus.Json.JsonInteger>();
                                    }
                                }

                                return default;
                            }
                        }

                        /// <summary>
                        /// Gets ObjectType.
                        /// </summary>
                        public Corvus.Json.JsonInteger ObjectType
                        {
                            get
                            {
                                if ((this.backing & Backing.JsonElement) != 0)
                                {
                                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                                    {
                                        return default;
                                    }

                                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.ObjectTypeUtf8, out JsonElement result))
                                    {
                                        return new Corvus.Json.JsonInteger(result);
                                    }
                                }

                                if ((this.backing & Backing.Object) != 0)
                                {
                                    if (this.objectBacking.TryGetValue(JsonPropertyNames.ObjectType, out JsonAny result))
                                    {
                                        return result.As<Corvus.Json.JsonInteger>();
                                    }
                                }

                                return default;
                            }
                        }

                        /// <summary>
                        /// Creates an instance of a <see cref = "ValueEntity"/>.
                        /// </summary>
                        public static ValueEntity Create(Corvus.Json.JsonInteger instanceNo, Corvus.Json.JsonInteger objectType)
                        {
                            var builder = ImmutableList.CreateBuilder<JsonObjectProperty>();
                            builder.Add(JsonPropertyNames.InstanceNo, instanceNo.AsAny);
                            builder.Add(JsonPropertyNames.ObjectType, objectType.AsAny);
                            return new(builder.ToImmutable());
                        }

                        /// <summary>
                        /// Sets InstanceNo.
                        /// </summary>
                        /// <param name = "value">The value to set.</param>
                        /// <returns>The entity with the updated property.</returns>
                        public ValueEntity WithInstanceNo(in Corvus.Json.JsonInteger value)
                        {
                            return this.SetProperty(JsonPropertyNames.InstanceNo, value);
                        }

                        /// <summary>
                        /// Sets ObjectType.
                        /// </summary>
                        /// <param name = "value">The value to set.</param>
                        /// <returns>The entity with the updated property.</returns>
                        public ValueEntity WithObjectType(in Corvus.Json.JsonInteger value)
                        {
                            return this.SetProperty(JsonPropertyNames.ObjectType, value);
                        }

                        private static ValidationContext __CorvusValidateObjectType(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
                        {
                            return property.ValueAs<Corvus.Json.JsonInteger>().Validate(validationContext, level);
                        }

                        private static ValidationContext __CorvusValidateInstanceNo(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
                        {
                            return property.ValueAs<Corvus.Json.JsonInteger>().Validate(validationContext, level);
                        }

                        /// <summary>
                        /// Tries to get the validator for the given property.
                        /// </summary>
                        /// <param name = "property">The property for which to get the validator.</param>
                        /// <param name = "hasJsonElementBacking"><c>True</c> if the object containing the property has a JsonElement backing.</param>
                        /// <param name = "propertyValidator">The validator for the property, if provided by this schema.</param>
                        /// <returns><c>True</c> if the validator was found.</returns>
                        private bool __TryGetCorvusLocalPropertiesValidator(in JsonObjectProperty property, bool hasJsonElementBacking, [NotNullWhen(true)] out ObjectPropertyValidator? propertyValidator)
                        {
                            if (hasJsonElementBacking)
                            {
                                if (property.NameEquals(JsonPropertyNames.ObjectTypeUtf8))
                                {
                                    propertyValidator = __CorvusValidateObjectType;
                                    return true;
                                }
                                else if (property.NameEquals(JsonPropertyNames.InstanceNoUtf8))
                                {
                                    propertyValidator = __CorvusValidateInstanceNo;
                                    return true;
                                }
                            }
                            else
                            {
                                if (property.NameEquals(JsonPropertyNames.ObjectType))
                                {
                                    propertyValidator = __CorvusValidateObjectType;
                                    return true;
                                }
                                else if (property.NameEquals(JsonPropertyNames.InstanceNo))
                                {
                                    propertyValidator = __CorvusValidateInstanceNo;
                                    return true;
                                }
                            }

                            propertyValidator = null;
                            return false;
                        }
                    }
                }
            }
        }
    }
}