//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Collections.Immutable;
using System.Runtime.CompilerServices;
using System.Text.Json;
using Corvus.Json;
using Corvus.Json.Internal;

namespace BuildingOS.Shared.Entities;
public readonly partial struct Dtdl
{
    /// <summary>
    /// A type generated from a JsonSchema specification.
    /// </summary>
    public readonly partial struct Model
    {
        /// <summary>
        /// Permitted values.
        /// </summary>
        public static class EnumValues
        {
            /// <summary>
            /// DtmiOrgW3IdRecRoom1.
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            public static readonly Model DtmiOrgW3IdRecRoom1 = Model.Parse("\"dtmi:org:w3id:rec:Room;1\"");
            /// <summary>
            /// Gets the DtmiOrgW3IdRecRoom1 as a raw UTF8 string.
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            public static ReadOnlySpan<byte> DtmiOrgW3IdRecRoom1Utf8 => "dtmi:org:w3id:rec:Room;1"u8;

            /// <summary>
            /// DtmiOrgBrickschemaSchemaBrickHVCEquipment1.
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            public static readonly Model DtmiOrgBrickschemaSchemaBrickHVCEquipment1 = Model.Parse("\"dtmi:org:brickschema:schema:brick:HVAC_Equipment;1\"");
            /// <summary>
            /// Gets the DtmiOrgBrickschemaSchemaBrickHVCEquipment1 as a raw UTF8 string.
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            public static ReadOnlySpan<byte> DtmiOrgBrickschemaSchemaBrickHVCEquipment1Utf8 => "dtmi:org:brickschema:schema:brick:HVAC_Equipment;1"u8;

            /// <summary>
            /// DtmiOrgBrickschemaSchemaBrickLighting1.
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            public static readonly Model DtmiOrgBrickschemaSchemaBrickLighting1 = Model.Parse("\"dtmi:org:brickschema:schema:brick:Lighting;1\"");
            /// <summary>
            /// Gets the DtmiOrgBrickschemaSchemaBrickLighting1 as a raw UTF8 string.
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            public static ReadOnlySpan<byte> DtmiOrgBrickschemaSchemaBrickLighting1Utf8 => "dtmi:org:brickschema:schema:brick:Lighting;1"u8;

            /// <summary>
            /// DtmiOrgW3IdRecSensorEquipment1.
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            public static readonly Model DtmiOrgW3IdRecSensorEquipment1 = Model.Parse("\"dtmi:org:w3id:rec:SensorEquipment;1\"");
            /// <summary>
            /// Gets the DtmiOrgW3IdRecSensorEquipment1 as a raw UTF8 string.
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            public static ReadOnlySpan<byte> DtmiOrgW3IdRecSensorEquipment1Utf8 => "dtmi:org:w3id:rec:SensorEquipment;1"u8;

            /// <summary>
            /// DtmiOrgW3IdRecLevel1.
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            public static readonly Model DtmiOrgW3IdRecLevel1 = Model.Parse("\"dtmi:org:w3id:rec:Level;1\"");
            /// <summary>
            /// Gets the DtmiOrgW3IdRecLevel1 as a raw UTF8 string.
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            public static ReadOnlySpan<byte> DtmiOrgW3IdRecLevel1Utf8 => "dtmi:org:w3id:rec:Level;1"u8;

            /// <summary>
            /// DtmiOrgW3IdRecSite1.
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            public static readonly Model DtmiOrgW3IdRecSite1 = Model.Parse("\"dtmi:org:w3id:rec:Site;1\"");
            /// <summary>
            /// Gets the DtmiOrgW3IdRecSite1 as a raw UTF8 string.
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            public static ReadOnlySpan<byte> DtmiOrgW3IdRecSite1Utf8 => "dtmi:org:w3id:rec:Site;1"u8;

            /// <summary>
            /// DtmiOrgW3IdRecBuilding1.
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            public static readonly Model DtmiOrgW3IdRecBuilding1 = Model.Parse("\"dtmi:org:w3id:rec:Building;1\"");
            /// <summary>
            /// Gets the DtmiOrgW3IdRecBuilding1 as a raw UTF8 string.
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            public static ReadOnlySpan<byte> DtmiOrgW3IdRecBuilding1Utf8 => "dtmi:org:w3id:rec:Building;1"u8;

            /// <summary>
            /// DtmiComAdtSampleOnOffSetting1.
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            public static readonly Model DtmiComAdtSampleOnOffSetting1 = Model.Parse("\"dtmi:com:adt:sample:OnOffSetting;1\"");
            /// <summary>
            /// Gets the DtmiComAdtSampleOnOffSetting1 as a raw UTF8 string.
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            public static ReadOnlySpan<byte> DtmiComAdtSampleOnOffSetting1Utf8 => "dtmi:com:adt:sample:OnOffSetting;1"u8;

            /// <summary>
            /// DtmiComAdtSampleOnOffState1.
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            public static readonly Model DtmiComAdtSampleOnOffState1 = Model.Parse("\"dtmi:com:adt:sample:OnOffState;1\"");
            /// <summary>
            /// Gets the DtmiComAdtSampleOnOffState1 as a raw UTF8 string.
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            public static ReadOnlySpan<byte> DtmiComAdtSampleOnOffState1Utf8 => "dtmi:com:adt:sample:OnOffState;1"u8;

            /// <summary>
            /// DtmiComAdtSampleSettingTemperatureSetting1.
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            public static readonly Model DtmiComAdtSampleSettingTemperatureSetting1 = Model.Parse("\"dtmi:com:adt:sample:SettingTemperatureSetting;1\"");
            /// <summary>
            /// Gets the DtmiComAdtSampleSettingTemperatureSetting1 as a raw UTF8 string.
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            public static ReadOnlySpan<byte> DtmiComAdtSampleSettingTemperatureSetting1Utf8 => "dtmi:com:adt:sample:SettingTemperatureSetting;1"u8;

            /// <summary>
            /// DtmiComAdtSampleSettingTemperatureState1.
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            public static readonly Model DtmiComAdtSampleSettingTemperatureState1 = Model.Parse("\"dtmi:com:adt:sample:SettingTemperatureState;1\"");
            /// <summary>
            /// Gets the DtmiComAdtSampleSettingTemperatureState1 as a raw UTF8 string.
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            public static ReadOnlySpan<byte> DtmiComAdtSampleSettingTemperatureState1Utf8 => "dtmi:com:adt:sample:SettingTemperatureState;1"u8;

            /// <summary>
            /// DtmiComAdtSampleOperationModeSetting1.
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            public static readonly Model DtmiComAdtSampleOperationModeSetting1 = Model.Parse("\"dtmi:com:adt:sample:OperationModeSetting;1\"");
            /// <summary>
            /// Gets the DtmiComAdtSampleOperationModeSetting1 as a raw UTF8 string.
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            public static ReadOnlySpan<byte> DtmiComAdtSampleOperationModeSetting1Utf8 => "dtmi:com:adt:sample:OperationModeSetting;1"u8;

            /// <summary>
            /// DtmiComAdtSampleOperationModeState1.
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            public static readonly Model DtmiComAdtSampleOperationModeState1 = Model.Parse("\"dtmi:com:adt:sample:OperationModeState;1\"");
            /// <summary>
            /// Gets the DtmiComAdtSampleOperationModeState1 as a raw UTF8 string.
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            public static ReadOnlySpan<byte> DtmiComAdtSampleOperationModeState1Utf8 => "dtmi:com:adt:sample:OperationModeState;1"u8;

            /// <summary>
            /// DtmiComAdtSampleFanSpeedSetting1.
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            public static readonly Model DtmiComAdtSampleFanSpeedSetting1 = Model.Parse("\"dtmi:com:adt:sample:FanSpeedSetting;1\"");
            /// <summary>
            /// Gets the DtmiComAdtSampleFanSpeedSetting1 as a raw UTF8 string.
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            public static ReadOnlySpan<byte> DtmiComAdtSampleFanSpeedSetting1Utf8 => "dtmi:com:adt:sample:FanSpeedSetting;1"u8;

            /// <summary>
            /// DtmiComAdtSampleFanSpeedState1.
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            public static readonly Model DtmiComAdtSampleFanSpeedState1 = Model.Parse("\"dtmi:com:adt:sample:FanSpeedState;1\"");
            /// <summary>
            /// Gets the DtmiComAdtSampleFanSpeedState1 as a raw UTF8 string.
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            public static ReadOnlySpan<byte> DtmiComAdtSampleFanSpeedState1Utf8 => "dtmi:com:adt:sample:FanSpeedState;1"u8;

            /// <summary>
            /// DtmiComAdtSampleFanDirectionSetting1.
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            public static readonly Model DtmiComAdtSampleFanDirectionSetting1 = Model.Parse("\"dtmi:com:adt:sample:FanDirectionSetting;1\"");
            /// <summary>
            /// Gets the DtmiComAdtSampleFanDirectionSetting1 as a raw UTF8 string.
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            public static ReadOnlySpan<byte> DtmiComAdtSampleFanDirectionSetting1Utf8 => "dtmi:com:adt:sample:FanDirectionSetting;1"u8;

            /// <summary>
            /// DtmiComAdtSampleFanDirectionState1.
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            public static readonly Model DtmiComAdtSampleFanDirectionState1 = Model.Parse("\"dtmi:com:adt:sample:FanDirectionState;1\"");
            /// <summary>
            /// Gets the DtmiComAdtSampleFanDirectionState1 as a raw UTF8 string.
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            public static ReadOnlySpan<byte> DtmiComAdtSampleFanDirectionState1Utf8 => "dtmi:com:adt:sample:FanDirectionState;1"u8;

            /// <summary>
            /// DtmiComAdtSampleOccupiedState1.
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            public static readonly Model DtmiComAdtSampleOccupiedState1 = Model.Parse("\"dtmi:com:adt:sample:OccupiedState;1\"");
            /// <summary>
            /// Gets the DtmiComAdtSampleOccupiedState1 as a raw UTF8 string.
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            public static ReadOnlySpan<byte> DtmiComAdtSampleOccupiedState1Utf8 => "dtmi:com:adt:sample:OccupiedState;1"u8;

            /// <summary>
            /// DtmiComAdtSampleSettingPatternSetting1.
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            public static readonly Model DtmiComAdtSampleSettingPatternSetting1 = Model.Parse("\"dtmi:com:adt:sample:SettingPatternSetting;1\"");
            /// <summary>
            /// Gets the DtmiComAdtSampleSettingPatternSetting1 as a raw UTF8 string.
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            public static ReadOnlySpan<byte> DtmiComAdtSampleSettingPatternSetting1Utf8 => "dtmi:com:adt:sample:SettingPatternSetting;1"u8;

            /// <summary>
            /// DtmiComAdtSampleSettingPatternState1.
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            public static readonly Model DtmiComAdtSampleSettingPatternState1 = Model.Parse("\"dtmi:com:adt:sample:SettingPatternState;1\"");
            /// <summary>
            /// Gets the DtmiComAdtSampleSettingPatternState1 as a raw UTF8 string.
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            public static ReadOnlySpan<byte> DtmiComAdtSampleSettingPatternState1Utf8 => "dtmi:com:adt:sample:SettingPatternState;1"u8;

            /// <summary>
            /// [{Title} || Item 0] (with predictable naming).
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            internal static readonly Model Item0 = Model.Parse("\"dtmi:org:w3id:rec:Room;1\"");
            /// <summary>
            /// [{Title} || Item 1] (with predictable naming).
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            internal static readonly Model Item1 = Model.Parse("\"dtmi:org:brickschema:schema:brick:HVAC_Equipment;1\"");
            /// <summary>
            /// [{Title} || Item 2] (with predictable naming).
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            internal static readonly Model Item2 = Model.Parse("\"dtmi:org:brickschema:schema:brick:Lighting;1\"");
            /// <summary>
            /// [{Title} || Item 3] (with predictable naming).
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            internal static readonly Model Item3 = Model.Parse("\"dtmi:org:w3id:rec:SensorEquipment;1\"");
            /// <summary>
            /// [{Title} || Item 4] (with predictable naming).
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            internal static readonly Model Item4 = Model.Parse("\"dtmi:org:w3id:rec:Level;1\"");
            /// <summary>
            /// [{Title} || Item 5] (with predictable naming).
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            internal static readonly Model Item5 = Model.Parse("\"dtmi:org:w3id:rec:Site;1\"");
            /// <summary>
            /// [{Title} || Item 6] (with predictable naming).
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            internal static readonly Model Item6 = Model.Parse("\"dtmi:org:w3id:rec:Building;1\"");
            /// <summary>
            /// [{Title} || Item 7] (with predictable naming).
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            internal static readonly Model Item7 = Model.Parse("\"dtmi:com:adt:sample:OnOffSetting;1\"");
            /// <summary>
            /// [{Title} || Item 8] (with predictable naming).
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            internal static readonly Model Item8 = Model.Parse("\"dtmi:com:adt:sample:OnOffState;1\"");
            /// <summary>
            /// [{Title} || Item 9] (with predictable naming).
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            internal static readonly Model Item9 = Model.Parse("\"dtmi:com:adt:sample:SettingTemperatureSetting;1\"");
            /// <summary>
            /// [{Title} || Item 10] (with predictable naming).
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            internal static readonly Model Item10 = Model.Parse("\"dtmi:com:adt:sample:SettingTemperatureState;1\"");
            /// <summary>
            /// [{Title} || Item 11] (with predictable naming).
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            internal static readonly Model Item11 = Model.Parse("\"dtmi:com:adt:sample:OperationModeSetting;1\"");
            /// <summary>
            /// [{Title} || Item 12] (with predictable naming).
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            internal static readonly Model Item12 = Model.Parse("\"dtmi:com:adt:sample:OperationModeState;1\"");
            /// <summary>
            /// [{Title} || Item 13] (with predictable naming).
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            internal static readonly Model Item13 = Model.Parse("\"dtmi:com:adt:sample:FanSpeedSetting;1\"");
            /// <summary>
            /// [{Title} || Item 14] (with predictable naming).
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            internal static readonly Model Item14 = Model.Parse("\"dtmi:com:adt:sample:FanSpeedState;1\"");
            /// <summary>
            /// [{Title} || Item 15] (with predictable naming).
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            internal static readonly Model Item15 = Model.Parse("\"dtmi:com:adt:sample:FanDirectionSetting;1\"");
            /// <summary>
            /// [{Title} || Item 16] (with predictable naming).
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            internal static readonly Model Item16 = Model.Parse("\"dtmi:com:adt:sample:FanDirectionState;1\"");
            /// <summary>
            /// [{Title} || Item 17] (with predictable naming).
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            internal static readonly Model Item17 = Model.Parse("\"dtmi:com:adt:sample:OccupiedState;1\"");
            /// <summary>
            /// [{Title} || Item 18] (with predictable naming).
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            internal static readonly Model Item18 = Model.Parse("\"dtmi:com:adt:sample:SettingPatternSetting;1\"");
            /// <summary>
            /// [{Title} || Item 19] (with predictable naming).
            /// </summary>
            /// <remarks>
            /// {Description}.
            /// </remarks>
            internal static readonly Model Item19 = Model.Parse("\"dtmi:com:adt:sample:SettingPatternState;1\"");
        }
    }
}