//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using Corvus.Json;

namespace BuildingOS.Shared.Entities;
public readonly partial struct Dtdl
{
    /// <summary>
    /// A type generated from a JsonSchema specification.
    /// </summary>
    public readonly partial struct IndigoSchema
    {
        /// <summary>
        /// Gets the value as a <see cref = "BuildingOS.Shared.Entities.Dtdl.FluffySchema"/>.
        /// </summary>
        public BuildingOS.Shared.Entities.Dtdl.FluffySchema AsFluffySchema
        {
            get
            {
                return (BuildingOS.Shared.Entities.Dtdl.FluffySchema)this;
            }
        }

        /// <summary>
        /// Gets a value indicating whether this is a valid <see cref = "BuildingOS.Shared.Entities.Dtdl.FluffySchema"/>.
        /// </summary>
        public bool IsFluffySchema
        {
            get
            {
                return ((BuildingOS.Shared.Entities.Dtdl.FluffySchema)this).IsValid();
            }
        }

        /// <summary>
        /// Gets the value as a <see cref = "BuildingOS.Shared.Entities.Dtdl.FluffySchema"/>.
        /// </summary>
        /// <param name = "result">The result of the conversion.</param>
        /// <returns><c>True</c> if the conversion was valid.</returns>
        public bool TryGetAsFluffySchema(out BuildingOS.Shared.Entities.Dtdl.FluffySchema result)
        {
            result = (BuildingOS.Shared.Entities.Dtdl.FluffySchema)this;
            return result.IsValid();
        }

        /// <summary>
        /// Gets a value indicating whether this is a valid <see cref = "Corvus.Json.JsonString"/>.
        /// </summary>
        public bool IsJsonString
        {
            get
            {
                return ((Corvus.Json.JsonString)this).IsValid();
            }
        }

        /// <summary>
        /// Gets the value as a <see cref = "Corvus.Json.JsonString"/>.
        /// </summary>
        /// <param name = "result">The result of the conversion.</param>
        /// <returns><c>True</c> if the conversion was valid.</returns>
        public bool TryGetAsJsonString(out Corvus.Json.JsonString result)
        {
            result = (Corvus.Json.JsonString)this;
            return result.IsValid();
        }
    }
}