//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Collections.Immutable;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using Corvus.Json;
using Corvus.Json.Internal;

namespace BuildingOS.Shared.Entities;
public readonly partial struct Dtdl
{
    /// <summary>
    /// A type generated from a JsonSchema specification.
    /// </summary>
    public readonly partial struct Building
    {
        private ValidationContext ValidateObject(JsonValueKind valueKind, in ValidationContext validationContext, ValidationLevel level)
        {
            ValidationContext result = validationContext;
            if (valueKind != JsonValueKind.Object)
            {
                return result;
            }

            int propertyCount = 0;
            bool foundBuildingAddress = false;
            bool foundCompositionType = false;
            bool foundDescription = false;
            bool foundElevationOfRefHeight = false;
            bool foundElevationOfTerrain = false;
            bool foundGlobalId = false;
            bool foundLongName = false;
            bool foundName = false;
            bool foundObjectType = false;
            foreach (JsonObjectProperty property in this.EnumerateObject())
            {
                if (__TryGetCorvusLocalPropertiesValidator(property, this.HasJsonElementBacking, out ObjectPropertyValidator? propertyValidator))
                {
                    result = result.WithLocalProperty(propertyCount);
                    if (level > ValidationLevel.Basic)
                    {
                        result = result.PushDocumentProperty("properties", property.Name.GetString());
                    }

                    var propertyResult = propertyValidator(property, result.CreateChildContext(), level);
                    result = result.MergeResults(propertyResult.IsValid, level, propertyResult);
                    if (level > ValidationLevel.Basic)
                    {
                        result = result.PopLocation(); // property name
                    }

                    if (level == ValidationLevel.Flag && !result.IsValid)
                    {
                        return result;
                    }

                    if ((this.HasJsonElementBacking && property.NameEquals(JsonPropertyNames.BuildingAddressUtf8)) || (!this.HasJsonElementBacking && property.NameEquals(JsonPropertyNames.BuildingAddress)))
                    {
                        foundBuildingAddress = true;
                    }
                    else if ((this.HasJsonElementBacking && property.NameEquals(JsonPropertyNames.CompositionTypeUtf8)) || (!this.HasJsonElementBacking && property.NameEquals(JsonPropertyNames.CompositionType)))
                    {
                        foundCompositionType = true;
                    }
                    else if ((this.HasJsonElementBacking && property.NameEquals(JsonPropertyNames.DescriptionUtf8)) || (!this.HasJsonElementBacking && property.NameEquals(JsonPropertyNames.Description)))
                    {
                        foundDescription = true;
                    }
                    else if ((this.HasJsonElementBacking && property.NameEquals(JsonPropertyNames.ElevationOfRefHeightUtf8)) || (!this.HasJsonElementBacking && property.NameEquals(JsonPropertyNames.ElevationOfRefHeight)))
                    {
                        foundElevationOfRefHeight = true;
                    }
                    else if ((this.HasJsonElementBacking && property.NameEquals(JsonPropertyNames.ElevationOfTerrainUtf8)) || (!this.HasJsonElementBacking && property.NameEquals(JsonPropertyNames.ElevationOfTerrain)))
                    {
                        foundElevationOfTerrain = true;
                    }
                    else if ((this.HasJsonElementBacking && property.NameEquals(JsonPropertyNames.GlobalIdUtf8)) || (!this.HasJsonElementBacking && property.NameEquals(JsonPropertyNames.GlobalId)))
                    {
                        foundGlobalId = true;
                    }
                    else if ((this.HasJsonElementBacking && property.NameEquals(JsonPropertyNames.LongNameUtf8)) || (!this.HasJsonElementBacking && property.NameEquals(JsonPropertyNames.LongName)))
                    {
                        foundLongName = true;
                    }
                    else if ((this.HasJsonElementBacking && property.NameEquals(JsonPropertyNames.NameUtf8)) || (!this.HasJsonElementBacking && property.NameEquals(JsonPropertyNames.Name)))
                    {
                        foundName = true;
                    }
                    else if ((this.HasJsonElementBacking && property.NameEquals(JsonPropertyNames.ObjectTypeUtf8)) || (!this.HasJsonElementBacking && property.NameEquals(JsonPropertyNames.ObjectType)))
                    {
                        foundObjectType = true;
                    }
                }

                if (!result.HasEvaluatedLocalProperty(propertyCount))
                {
                    if (level >= ValidationLevel.Detailed)
                    {
                        result = result.WithResult(isValid: false, $"9.3.2.3. additionalProperties - additional property \"{property.Name}\" is not permitted.");
                    }
                    else if (level >= ValidationLevel.Basic)
                    {
                        result = result.WithResult(isValid: false, "9.3.2.3. additionalProperties - additional properties are not permitted.");
                    }
                    else
                    {
                        return result.WithResult(isValid: false);
                    }
                }

                propertyCount++;
            }

            if (!foundBuildingAddress)
            {
                if (level >= ValidationLevel.Detailed)
                {
                    result = result.WithResult(isValid: false, $"6.5.3. required - required property \"BuildingAddress\" not present.");
                }
                else if (level >= ValidationLevel.Basic)
                {
                    result = result.WithResult(isValid: false, "6.5.3. required - required property not present.");
                }
                else
                {
                    return result.WithResult(isValid: false);
                }
            }

            if (!foundCompositionType)
            {
                if (level >= ValidationLevel.Detailed)
                {
                    result = result.WithResult(isValid: false, $"6.5.3. required - required property \"CompositionType\" not present.");
                }
                else if (level >= ValidationLevel.Basic)
                {
                    result = result.WithResult(isValid: false, "6.5.3. required - required property not present.");
                }
                else
                {
                    return result.WithResult(isValid: false);
                }
            }

            if (!foundDescription)
            {
                if (level >= ValidationLevel.Detailed)
                {
                    result = result.WithResult(isValid: false, $"6.5.3. required - required property \"Description\" not present.");
                }
                else if (level >= ValidationLevel.Basic)
                {
                    result = result.WithResult(isValid: false, "6.5.3. required - required property not present.");
                }
                else
                {
                    return result.WithResult(isValid: false);
                }
            }

            if (!foundElevationOfRefHeight)
            {
                if (level >= ValidationLevel.Detailed)
                {
                    result = result.WithResult(isValid: false, $"6.5.3. required - required property \"ElevationOfRefHeight\" not present.");
                }
                else if (level >= ValidationLevel.Basic)
                {
                    result = result.WithResult(isValid: false, "6.5.3. required - required property not present.");
                }
                else
                {
                    return result.WithResult(isValid: false);
                }
            }

            if (!foundElevationOfTerrain)
            {
                if (level >= ValidationLevel.Detailed)
                {
                    result = result.WithResult(isValid: false, $"6.5.3. required - required property \"ElevationOfTerrain\" not present.");
                }
                else if (level >= ValidationLevel.Basic)
                {
                    result = result.WithResult(isValid: false, "6.5.3. required - required property not present.");
                }
                else
                {
                    return result.WithResult(isValid: false);
                }
            }

            if (!foundGlobalId)
            {
                if (level >= ValidationLevel.Detailed)
                {
                    result = result.WithResult(isValid: false, $"6.5.3. required - required property \"GlobalId\" not present.");
                }
                else if (level >= ValidationLevel.Basic)
                {
                    result = result.WithResult(isValid: false, "6.5.3. required - required property not present.");
                }
                else
                {
                    return result.WithResult(isValid: false);
                }
            }

            if (!foundLongName)
            {
                if (level >= ValidationLevel.Detailed)
                {
                    result = result.WithResult(isValid: false, $"6.5.3. required - required property \"LongName\" not present.");
                }
                else if (level >= ValidationLevel.Basic)
                {
                    result = result.WithResult(isValid: false, "6.5.3. required - required property not present.");
                }
                else
                {
                    return result.WithResult(isValid: false);
                }
            }

            if (!foundName)
            {
                if (level >= ValidationLevel.Detailed)
                {
                    result = result.WithResult(isValid: false, $"6.5.3. required - required property \"Name\" not present.");
                }
                else if (level >= ValidationLevel.Basic)
                {
                    result = result.WithResult(isValid: false, "6.5.3. required - required property not present.");
                }
                else
                {
                    return result.WithResult(isValid: false);
                }
            }

            if (!foundObjectType)
            {
                if (level >= ValidationLevel.Detailed)
                {
                    result = result.WithResult(isValid: false, $"6.5.3. required - required property \"ObjectType\" not present.");
                }
                else if (level >= ValidationLevel.Basic)
                {
                    result = result.WithResult(isValid: false, "6.5.3. required - required property not present.");
                }
                else
                {
                    return result.WithResult(isValid: false);
                }
            }

            return result;
        }
    }
}