//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Text.Json;
using Corvus.Json;
using Corvus.Json.Internal;

namespace BuildingOS.Shared.Entities;
public readonly partial struct Dtdl
{
    /// <summary>
    /// A type generated from a JsonSchema specification.
    /// </summary>
    public readonly partial struct Content
    {
        /// <summary>
        /// The well-known property names in the JSON object.
        /// </summary>
        public static class JsonPropertyNames
        {
            /// <summary>
            /// JSON property name for <see cref = "Name"/>.
            /// </summary>
            public static ReadOnlySpan<byte> NameUtf8 => "name"u8;

            /// <summary>
            /// JSON property name for <see cref = "Name"/>.
            /// </summary>
            public const string Name = "name";
            /// <summary>
            /// JSON property name for <see cref = "Schema"/>.
            /// </summary>
            public static ReadOnlySpan<byte> SchemaUtf8 => "schema"u8;

            /// <summary>
            /// JSON property name for <see cref = "Schema"/>.
            /// </summary>
            public const string Schema = "schema";
            /// <summary>
            /// JSON property name for <see cref = "Target"/>.
            /// </summary>
            public static ReadOnlySpan<byte> TargetUtf8 => "target"u8;

            /// <summary>
            /// JSON property name for <see cref = "Target"/>.
            /// </summary>
            public const string Target = "target";
            /// <summary>
            /// JSON property name for <see cref = "Type"/>.
            /// </summary>
            public static ReadOnlySpan<byte> TypeUtf8 => "@type"u8;

            /// <summary>
            /// JSON property name for <see cref = "Type"/>.
            /// </summary>
            public const string Type = "@type";
            /// <summary>
            /// JSON property name for <see cref = "Writable"/>.
            /// </summary>
            public static ReadOnlySpan<byte> WritableUtf8 => "writable"u8;

            /// <summary>
            /// JSON property name for <see cref = "Writable"/>.
            /// </summary>
            public const string Writable = "writable";
        }

        /// <summary>
        /// Gets Name.
        /// </summary>
        public Corvus.Json.JsonString Name
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.NameUtf8, out JsonElement result))
                    {
                        return new Corvus.Json.JsonString(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.Name, out JsonAny result))
                    {
                        return result.As<Corvus.Json.JsonString>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets Schema.
        /// </summary>
        public BuildingOS.Shared.Entities.Dtdl.ContentSchema Schema
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.SchemaUtf8, out JsonElement result))
                    {
                        return new BuildingOS.Shared.Entities.Dtdl.ContentSchema(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.Schema, out JsonAny result))
                    {
                        return result.As<BuildingOS.Shared.Entities.Dtdl.ContentSchema>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets Target.
        /// </summary>
        public BuildingOS.Shared.Entities.Dtdl.Model Target
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.TargetUtf8, out JsonElement result))
                    {
                        return new BuildingOS.Shared.Entities.Dtdl.Model(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.Target, out JsonAny result))
                    {
                        return result.As<BuildingOS.Shared.Entities.Dtdl.Model>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets Type.
        /// </summary>
        public Corvus.Json.JsonString Type
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.TypeUtf8, out JsonElement result))
                    {
                        return new Corvus.Json.JsonString(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.Type, out JsonAny result))
                    {
                        return result.As<Corvus.Json.JsonString>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets Writable.
        /// </summary>
        public Corvus.Json.JsonBoolean Writable
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.WritableUtf8, out JsonElement result))
                    {
                        return new Corvus.Json.JsonBoolean(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.Writable, out JsonAny result))
                    {
                        return result.As<Corvus.Json.JsonBoolean>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Creates an instance of a <see cref = "Content"/>.
        /// </summary>
        public static Content Create(Corvus.Json.JsonString name, Corvus.Json.JsonString type, BuildingOS.Shared.Entities.Dtdl.ContentSchema? schema = null, BuildingOS.Shared.Entities.Dtdl.Model? target = null, Corvus.Json.JsonBoolean? writable = null)
        {
            var builder = ImmutableList.CreateBuilder<JsonObjectProperty>();
            builder.Add(JsonPropertyNames.Name, name.AsAny);
            builder.Add(JsonPropertyNames.Type, type.AsAny);
            if (schema is BuildingOS.Shared.Entities.Dtdl.ContentSchema schema__)
            {
                builder.Add(JsonPropertyNames.Schema, schema__.AsAny);
            }

            if (target is BuildingOS.Shared.Entities.Dtdl.Model target__)
            {
                builder.Add(JsonPropertyNames.Target, target__.AsAny);
            }

            if (writable is Corvus.Json.JsonBoolean writable__)
            {
                builder.Add(JsonPropertyNames.Writable, writable__.AsAny);
            }

            return new(builder.ToImmutable());
        }

        /// <summary>
        /// Sets name.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public Content WithName(in Corvus.Json.JsonString value)
        {
            return this.SetProperty(JsonPropertyNames.Name, value);
        }

        /// <summary>
        /// Sets schema.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public Content WithSchema(in BuildingOS.Shared.Entities.Dtdl.ContentSchema value)
        {
            return this.SetProperty(JsonPropertyNames.Schema, value);
        }

        /// <summary>
        /// Sets target.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public Content WithTarget(in BuildingOS.Shared.Entities.Dtdl.Model value)
        {
            return this.SetProperty(JsonPropertyNames.Target, value);
        }

        /// <summary>
        /// Sets @type.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public Content WithType(in Corvus.Json.JsonString value)
        {
            return this.SetProperty(JsonPropertyNames.Type, value);
        }

        /// <summary>
        /// Sets writable.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public Content WithWritable(in Corvus.Json.JsonBoolean value)
        {
            return this.SetProperty(JsonPropertyNames.Writable, value);
        }

        private static ValidationContext __CorvusValidateType(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Corvus.Json.JsonString>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateName(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Corvus.Json.JsonString>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateSchema(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<BuildingOS.Shared.Entities.Dtdl.ContentSchema>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateTarget(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<BuildingOS.Shared.Entities.Dtdl.Model>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateWritable(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Corvus.Json.JsonBoolean>().Validate(validationContext, level);
        }

        /// <summary>
        /// Tries to get the validator for the given property.
        /// </summary>
        /// <param name = "property">The property for which to get the validator.</param>
        /// <param name = "hasJsonElementBacking"><c>True</c> if the object containing the property has a JsonElement backing.</param>
        /// <param name = "propertyValidator">The validator for the property, if provided by this schema.</param>
        /// <returns><c>True</c> if the validator was found.</returns>
        private bool __TryGetCorvusLocalPropertiesValidator(in JsonObjectProperty property, bool hasJsonElementBacking, [NotNullWhen(true)] out ObjectPropertyValidator? propertyValidator)
        {
            if (hasJsonElementBacking)
            {
                if (property.NameEquals(JsonPropertyNames.TypeUtf8))
                {
                    propertyValidator = __CorvusValidateType;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.NameUtf8))
                {
                    propertyValidator = __CorvusValidateName;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.SchemaUtf8))
                {
                    propertyValidator = __CorvusValidateSchema;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.TargetUtf8))
                {
                    propertyValidator = __CorvusValidateTarget;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.WritableUtf8))
                {
                    propertyValidator = __CorvusValidateWritable;
                    return true;
                }
            }
            else
            {
                if (property.NameEquals(JsonPropertyNames.Type))
                {
                    propertyValidator = __CorvusValidateType;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.Name))
                {
                    propertyValidator = __CorvusValidateName;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.Schema))
                {
                    propertyValidator = __CorvusValidateSchema;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.Target))
                {
                    propertyValidator = __CorvusValidateTarget;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.Writable))
                {
                    propertyValidator = __CorvusValidateWritable;
                    return true;
                }
            }

            propertyValidator = null;
            return false;
        }
    }
}