//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Text.Json;
using Corvus.Json;
using Corvus.Json.Internal;

namespace BuildingOS.Shared.Entities;
public readonly partial struct Dtdl
{
    /// <summary>
    /// A type generated from a JsonSchema specification.
    /// </summary>
    public readonly partial struct OccupiedStatePresentValue
    {
        /// <summary>
        /// The well-known property names in the JSON object.
        /// </summary>
        public static class JsonPropertyNames
        {
            /// <summary>
            /// JSON property name for <see cref = "Timestamp"/>.
            /// </summary>
            public static ReadOnlySpan<byte> TimestampUtf8 => "Timestamp"u8;

            /// <summary>
            /// JSON property name for <see cref = "Timestamp"/>.
            /// </summary>
            public const string Timestamp = "Timestamp";
            /// <summary>
            /// JSON property name for <see cref = "Value"/>.
            /// </summary>
            public static ReadOnlySpan<byte> ValueUtf8 => "Value"u8;

            /// <summary>
            /// JSON property name for <see cref = "Value"/>.
            /// </summary>
            public const string Value = "Value";
        }

        /// <summary>
        /// Gets Timestamp.
        /// </summary>
        public Corvus.Json.JsonDateTime Timestamp
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.TimestampUtf8, out JsonElement result))
                    {
                        return new Corvus.Json.JsonDateTime(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.Timestamp, out JsonAny result))
                    {
                        return result.As<Corvus.Json.JsonDateTime>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets Value.
        /// </summary>
        public Corvus.Json.JsonBoolean Value
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.ValueUtf8, out JsonElement result))
                    {
                        return new Corvus.Json.JsonBoolean(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.Value, out JsonAny result))
                    {
                        return result.As<Corvus.Json.JsonBoolean>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Creates an instance of a <see cref = "OccupiedStatePresentValue"/>.
        /// </summary>
        public static OccupiedStatePresentValue Create(Corvus.Json.JsonDateTime timestamp, Corvus.Json.JsonBoolean value)
        {
            var builder = ImmutableList.CreateBuilder<JsonObjectProperty>();
            builder.Add(JsonPropertyNames.Timestamp, timestamp.AsAny);
            builder.Add(JsonPropertyNames.Value, value.AsAny);
            return new(builder.ToImmutable());
        }

        /// <summary>
        /// Sets Timestamp.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public OccupiedStatePresentValue WithTimestamp(in Corvus.Json.JsonDateTime value)
        {
            return this.SetProperty(JsonPropertyNames.Timestamp, value);
        }

        /// <summary>
        /// Sets Value.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public OccupiedStatePresentValue WithValue(in Corvus.Json.JsonBoolean value)
        {
            return this.SetProperty(JsonPropertyNames.Value, value);
        }

        private static ValidationContext __CorvusValidateTimestamp(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Corvus.Json.JsonDateTime>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateValue(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Corvus.Json.JsonBoolean>().Validate(validationContext, level);
        }

        /// <summary>
        /// Tries to get the validator for the given property.
        /// </summary>
        /// <param name = "property">The property for which to get the validator.</param>
        /// <param name = "hasJsonElementBacking"><c>True</c> if the object containing the property has a JsonElement backing.</param>
        /// <param name = "propertyValidator">The validator for the property, if provided by this schema.</param>
        /// <returns><c>True</c> if the validator was found.</returns>
        private bool __TryGetCorvusLocalPropertiesValidator(in JsonObjectProperty property, bool hasJsonElementBacking, [NotNullWhen(true)] out ObjectPropertyValidator? propertyValidator)
        {
            if (hasJsonElementBacking)
            {
                if (property.NameEquals(JsonPropertyNames.TimestampUtf8))
                {
                    propertyValidator = __CorvusValidateTimestamp;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.ValueUtf8))
                {
                    propertyValidator = __CorvusValidateValue;
                    return true;
                }
            }
            else
            {
                if (property.NameEquals(JsonPropertyNames.Timestamp))
                {
                    propertyValidator = __CorvusValidateTimestamp;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.Value))
                {
                    propertyValidator = __CorvusValidateValue;
                    return true;
                }
            }

            propertyValidator = null;
            return false;
        }
    }
}