//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Text.Json;
using Corvus.Json;
using Corvus.Json.Internal;

namespace BuildingOS.Shared.Entities;
public readonly partial struct Dtdl
{
    /// <summary>
    /// A type generated from a JsonSchema specification.
    /// </summary>
    public readonly partial struct DigitalTwinsGraph
    {
        /// <summary>
        /// The well-known property names in the JSON object.
        /// </summary>
        public static class JsonPropertyNames
        {
            /// <summary>
            /// JSON property name for <see cref = "DigitalTwins"/>.
            /// </summary>
            public static ReadOnlySpan<byte> DigitalTwinsUtf8 => "digitalTwins"u8;

            /// <summary>
            /// JSON property name for <see cref = "DigitalTwins"/>.
            /// </summary>
            public const string DigitalTwins = "digitalTwins";
            /// <summary>
            /// JSON property name for <see cref = "Relationships"/>.
            /// </summary>
            public static ReadOnlySpan<byte> RelationshipsUtf8 => "relationships"u8;

            /// <summary>
            /// JSON property name for <see cref = "Relationships"/>.
            /// </summary>
            public const string Relationships = "relationships";
        }

        /// <summary>
        /// Gets DigitalTwins.
        /// </summary>
        public BuildingOS.Shared.Entities.Dtdl.DigitalTwinsGraph.DigitalTwinArray DigitalTwins
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.DigitalTwinsUtf8, out JsonElement result))
                    {
                        return new BuildingOS.Shared.Entities.Dtdl.DigitalTwinsGraph.DigitalTwinArray(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.DigitalTwins, out JsonAny result))
                    {
                        return result.As<BuildingOS.Shared.Entities.Dtdl.DigitalTwinsGraph.DigitalTwinArray>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets Relationships.
        /// </summary>
        public BuildingOS.Shared.Entities.Dtdl.DigitalTwinsGraph.RelationshipArray Relationships
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.RelationshipsUtf8, out JsonElement result))
                    {
                        return new BuildingOS.Shared.Entities.Dtdl.DigitalTwinsGraph.RelationshipArray(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.Relationships, out JsonAny result))
                    {
                        return result.As<BuildingOS.Shared.Entities.Dtdl.DigitalTwinsGraph.RelationshipArray>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Creates an instance of a <see cref = "DigitalTwinsGraph"/>.
        /// </summary>
        public static DigitalTwinsGraph Create(BuildingOS.Shared.Entities.Dtdl.DigitalTwinsGraph.DigitalTwinArray digitalTwins, BuildingOS.Shared.Entities.Dtdl.DigitalTwinsGraph.RelationshipArray relationships)
        {
            var builder = ImmutableList.CreateBuilder<JsonObjectProperty>();
            builder.Add(JsonPropertyNames.DigitalTwins, digitalTwins.AsAny);
            builder.Add(JsonPropertyNames.Relationships, relationships.AsAny);
            return new(builder.ToImmutable());
        }

        /// <summary>
        /// Sets digitalTwins.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public DigitalTwinsGraph WithDigitalTwins(in BuildingOS.Shared.Entities.Dtdl.DigitalTwinsGraph.DigitalTwinArray value)
        {
            return this.SetProperty(JsonPropertyNames.DigitalTwins, value);
        }

        /// <summary>
        /// Sets relationships.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public DigitalTwinsGraph WithRelationships(in BuildingOS.Shared.Entities.Dtdl.DigitalTwinsGraph.RelationshipArray value)
        {
            return this.SetProperty(JsonPropertyNames.Relationships, value);
        }

        private static ValidationContext __CorvusValidateDigitalTwins(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<BuildingOS.Shared.Entities.Dtdl.DigitalTwinsGraph.DigitalTwinArray>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateRelationships(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<BuildingOS.Shared.Entities.Dtdl.DigitalTwinsGraph.RelationshipArray>().Validate(validationContext, level);
        }

        /// <summary>
        /// Tries to get the validator for the given property.
        /// </summary>
        /// <param name = "property">The property for which to get the validator.</param>
        /// <param name = "hasJsonElementBacking"><c>True</c> if the object containing the property has a JsonElement backing.</param>
        /// <param name = "propertyValidator">The validator for the property, if provided by this schema.</param>
        /// <returns><c>True</c> if the validator was found.</returns>
        private bool __TryGetCorvusLocalPropertiesValidator(in JsonObjectProperty property, bool hasJsonElementBacking, [NotNullWhen(true)] out ObjectPropertyValidator? propertyValidator)
        {
            if (hasJsonElementBacking)
            {
                if (property.NameEquals(JsonPropertyNames.DigitalTwinsUtf8))
                {
                    propertyValidator = __CorvusValidateDigitalTwins;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.RelationshipsUtf8))
                {
                    propertyValidator = __CorvusValidateRelationships;
                    return true;
                }
            }
            else
            {
                if (property.NameEquals(JsonPropertyNames.DigitalTwins))
                {
                    propertyValidator = __CorvusValidateDigitalTwins;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.Relationships))
                {
                    propertyValidator = __CorvusValidateRelationships;
                    return true;
                }
            }

            propertyValidator = null;
            return false;
        }
    }
}