//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Text.Json;
using Corvus.Json;
using Corvus.Json.Internal;

namespace BuildingOS.Shared.Entities;
/// <summary>
/// A type generated from a JsonSchema specification.
/// </summary>
public readonly partial struct Dtdl
{
    /// <summary>
    /// The well-known property names in the JSON object.
    /// </summary>
    public static class JsonPropertyNames
    {
        /// <summary>
        /// JSON property name for <see cref = "DigitalTwinsFileInfoValue"/>.
        /// </summary>
        public static ReadOnlySpan<byte> DigitalTwinsFileInfoValueUtf8 => "digitalTwinsFileInfo"u8;

        /// <summary>
        /// JSON property name for <see cref = "DigitalTwinsFileInfoValue"/>.
        /// </summary>
        public const string DigitalTwinsFileInfoValue = "digitalTwinsFileInfo";
        /// <summary>
        /// JSON property name for <see cref = "DigitalTwinsGraphValue"/>.
        /// </summary>
        public static ReadOnlySpan<byte> DigitalTwinsGraphValueUtf8 => "digitalTwinsGraph"u8;

        /// <summary>
        /// JSON property name for <see cref = "DigitalTwinsGraphValue"/>.
        /// </summary>
        public const string DigitalTwinsGraphValue = "digitalTwinsGraph";
        /// <summary>
        /// JSON property name for <see cref = "DigitalTwinsModels"/>.
        /// </summary>
        public static ReadOnlySpan<byte> DigitalTwinsModelsUtf8 => "digitalTwinsModels"u8;

        /// <summary>
        /// JSON property name for <see cref = "DigitalTwinsModels"/>.
        /// </summary>
        public const string DigitalTwinsModels = "digitalTwinsModels";
    }

    /// <summary>
    /// Gets DigitalTwinsFileInfoValue.
    /// </summary>
    public BuildingOS.Shared.Entities.Dtdl.DigitalTwinsFileInfo DigitalTwinsFileInfoValue
    {
        get
        {
            if ((this.backing & Backing.JsonElement) != 0)
            {
                if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                {
                    return default;
                }

                if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.DigitalTwinsFileInfoValueUtf8, out JsonElement result))
                {
                    return new BuildingOS.Shared.Entities.Dtdl.DigitalTwinsFileInfo(result);
                }
            }

            if ((this.backing & Backing.Object) != 0)
            {
                if (this.objectBacking.TryGetValue(JsonPropertyNames.DigitalTwinsFileInfoValue, out JsonAny result))
                {
                    return result.As<BuildingOS.Shared.Entities.Dtdl.DigitalTwinsFileInfo>();
                }
            }

            return default;
        }
    }

    /// <summary>
    /// Gets DigitalTwinsGraphValue.
    /// </summary>
    public BuildingOS.Shared.Entities.Dtdl.DigitalTwinsGraph DigitalTwinsGraphValue
    {
        get
        {
            if ((this.backing & Backing.JsonElement) != 0)
            {
                if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                {
                    return default;
                }

                if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.DigitalTwinsGraphValueUtf8, out JsonElement result))
                {
                    return new BuildingOS.Shared.Entities.Dtdl.DigitalTwinsGraph(result);
                }
            }

            if ((this.backing & Backing.Object) != 0)
            {
                if (this.objectBacking.TryGetValue(JsonPropertyNames.DigitalTwinsGraphValue, out JsonAny result))
                {
                    return result.As<BuildingOS.Shared.Entities.Dtdl.DigitalTwinsGraph>();
                }
            }

            return default;
        }
    }

    /// <summary>
    /// Gets DigitalTwinsModels.
    /// </summary>
    public BuildingOS.Shared.Entities.Dtdl.DigitalTwinsModelArray DigitalTwinsModels
    {
        get
        {
            if ((this.backing & Backing.JsonElement) != 0)
            {
                if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                {
                    return default;
                }

                if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.DigitalTwinsModelsUtf8, out JsonElement result))
                {
                    return new BuildingOS.Shared.Entities.Dtdl.DigitalTwinsModelArray(result);
                }
            }

            if ((this.backing & Backing.Object) != 0)
            {
                if (this.objectBacking.TryGetValue(JsonPropertyNames.DigitalTwinsModels, out JsonAny result))
                {
                    return result.As<BuildingOS.Shared.Entities.Dtdl.DigitalTwinsModelArray>();
                }
            }

            return default;
        }
    }

    /// <summary>
    /// Creates an instance of a <see cref = "Dtdl"/>.
    /// </summary>
    public static Dtdl Create(BuildingOS.Shared.Entities.Dtdl.DigitalTwinsFileInfo digitalTwinsFileInfoValue, BuildingOS.Shared.Entities.Dtdl.DigitalTwinsGraph digitalTwinsGraphValue, BuildingOS.Shared.Entities.Dtdl.DigitalTwinsModelArray digitalTwinsModels)
    {
        var builder = ImmutableList.CreateBuilder<JsonObjectProperty>();
        builder.Add(JsonPropertyNames.DigitalTwinsFileInfoValue, digitalTwinsFileInfoValue.AsAny);
        builder.Add(JsonPropertyNames.DigitalTwinsGraphValue, digitalTwinsGraphValue.AsAny);
        builder.Add(JsonPropertyNames.DigitalTwinsModels, digitalTwinsModels.AsAny);
        return new(builder.ToImmutable());
    }

    /// <summary>
    /// Sets digitalTwinsFileInfo.
    /// </summary>
    /// <param name = "value">The value to set.</param>
    /// <returns>The entity with the updated property.</returns>
    public Dtdl WithDigitalTwinsFileInfoValue(in BuildingOS.Shared.Entities.Dtdl.DigitalTwinsFileInfo value)
    {
        return this.SetProperty(JsonPropertyNames.DigitalTwinsFileInfoValue, value);
    }

    /// <summary>
    /// Sets digitalTwinsGraph.
    /// </summary>
    /// <param name = "value">The value to set.</param>
    /// <returns>The entity with the updated property.</returns>
    public Dtdl WithDigitalTwinsGraphValue(in BuildingOS.Shared.Entities.Dtdl.DigitalTwinsGraph value)
    {
        return this.SetProperty(JsonPropertyNames.DigitalTwinsGraphValue, value);
    }

    /// <summary>
    /// Sets digitalTwinsModels.
    /// </summary>
    /// <param name = "value">The value to set.</param>
    /// <returns>The entity with the updated property.</returns>
    public Dtdl WithDigitalTwinsModels(in BuildingOS.Shared.Entities.Dtdl.DigitalTwinsModelArray value)
    {
        return this.SetProperty(JsonPropertyNames.DigitalTwinsModels, value);
    }

    private static ValidationContext __CorvusValidateDigitalTwinsFileInfoValue(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
    {
        return property.ValueAs<BuildingOS.Shared.Entities.Dtdl.DigitalTwinsFileInfo>().Validate(validationContext, level);
    }

    private static ValidationContext __CorvusValidateDigitalTwinsGraphValue(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
    {
        return property.ValueAs<BuildingOS.Shared.Entities.Dtdl.DigitalTwinsGraph>().Validate(validationContext, level);
    }

    private static ValidationContext __CorvusValidateDigitalTwinsModels(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
    {
        return property.ValueAs<BuildingOS.Shared.Entities.Dtdl.DigitalTwinsModelArray>().Validate(validationContext, level);
    }

    /// <summary>
    /// Tries to get the validator for the given property.
    /// </summary>
    /// <param name = "property">The property for which to get the validator.</param>
    /// <param name = "hasJsonElementBacking"><c>True</c> if the object containing the property has a JsonElement backing.</param>
    /// <param name = "propertyValidator">The validator for the property, if provided by this schema.</param>
    /// <returns><c>True</c> if the validator was found.</returns>
    private bool __TryGetCorvusLocalPropertiesValidator(in JsonObjectProperty property, bool hasJsonElementBacking, [NotNullWhen(true)] out ObjectPropertyValidator? propertyValidator)
    {
        if (hasJsonElementBacking)
        {
            if (property.NameEquals(JsonPropertyNames.DigitalTwinsFileInfoValueUtf8))
            {
                propertyValidator = __CorvusValidateDigitalTwinsFileInfoValue;
                return true;
            }
            else if (property.NameEquals(JsonPropertyNames.DigitalTwinsGraphValueUtf8))
            {
                propertyValidator = __CorvusValidateDigitalTwinsGraphValue;
                return true;
            }
            else if (property.NameEquals(JsonPropertyNames.DigitalTwinsModelsUtf8))
            {
                propertyValidator = __CorvusValidateDigitalTwinsModels;
                return true;
            }
        }
        else
        {
            if (property.NameEquals(JsonPropertyNames.DigitalTwinsFileInfoValue))
            {
                propertyValidator = __CorvusValidateDigitalTwinsFileInfoValue;
                return true;
            }
            else if (property.NameEquals(JsonPropertyNames.DigitalTwinsGraphValue))
            {
                propertyValidator = __CorvusValidateDigitalTwinsGraphValue;
                return true;
            }
            else if (property.NameEquals(JsonPropertyNames.DigitalTwinsModels))
            {
                propertyValidator = __CorvusValidateDigitalTwinsModels;
                return true;
            }
        }

        propertyValidator = null;
        return false;
    }
}