//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Collections.Immutable;
using System.Text.Json;
using Corvus.Json;
using Corvus.Json.Internal;

namespace BuildingOS.Shared.Entities;
public readonly partial struct Dtdl
{
    /// <summary>
    /// A type generated from a JsonSchema specification.
    /// </summary>
    public readonly partial struct IndigoSchema
    {
        /// <summary>
        /// Conversion to <see cref = "BuildingOS.Shared.Entities.Dtdl.FluffySchema"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static explicit operator BuildingOS.Shared.Entities.Dtdl.FluffySchema(IndigoSchema value)
        {
            if ((value.backing & Backing.JsonElement) != 0)
            {
                return new(value.AsJsonElement);
            }

            if ((value.backing & Backing.Object) != 0)
            {
                return new(value.objectBacking);
            }

            return BuildingOS.Shared.Entities.Dtdl.FluffySchema.Undefined;
        }

        /// <summary>
        /// Conversion from <see cref = "BuildingOS.Shared.Entities.Dtdl.FluffySchema"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static implicit operator IndigoSchema(BuildingOS.Shared.Entities.Dtdl.FluffySchema value)
        {
            if (value.HasJsonElementBacking)
            {
                return new(value.AsJsonElement);
            }

            return value.ValueKind switch
            {
                JsonValueKind.Object => new(value.AsPropertyBacking()),
                _ => Undefined
            };
        }

        /// <summary>
        /// Conversion to <see cref = "Corvus.Json.JsonString"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static explicit operator Corvus.Json.JsonString(IndigoSchema value)
        {
            if ((value.backing & Backing.JsonElement) != 0)
            {
                return new(value.AsJsonElement);
            }

            if ((value.backing & Backing.String) != 0)
            {
                return new(value.stringBacking);
            }

            return Corvus.Json.JsonString.Undefined;
        }
    }
}