//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Text.Json;
using Corvus.Json;
using Corvus.Json.Internal;

namespace BuildingOS.Shared.Entities;
public readonly partial struct Dtdl
{
    /// <summary>
    /// A type generated from a JsonSchema specification.
    /// </summary>
    public readonly partial struct Metadata
    {
        /// <summary>
        /// The well-known property names in the JSON object.
        /// </summary>
        public static class JsonPropertyNames
        {
            /// <summary>
            /// JSON property name for <see cref = "Model"/>.
            /// </summary>
            public static ReadOnlySpan<byte> ModelUtf8 => "$model"u8;

            /// <summary>
            /// JSON property name for <see cref = "Model"/>.
            /// </summary>
            public const string Model = "$model";
        }

        /// <summary>
        /// Gets Model.
        /// </summary>
        public BuildingOS.Shared.Entities.Dtdl.Model Model
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.ModelUtf8, out JsonElement result))
                    {
                        return new BuildingOS.Shared.Entities.Dtdl.Model(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.Model, out JsonAny result))
                    {
                        return result.As<BuildingOS.Shared.Entities.Dtdl.Model>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Creates an instance of a <see cref = "Metadata"/>.
        /// </summary>
        public static Metadata Create(BuildingOS.Shared.Entities.Dtdl.Model model)
        {
            var builder = ImmutableList.CreateBuilder<JsonObjectProperty>();
            builder.Add(JsonPropertyNames.Model, model.AsAny);
            return new(builder.ToImmutable());
        }

        /// <summary>
        /// Sets $model.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public Metadata WithModel(in BuildingOS.Shared.Entities.Dtdl.Model value)
        {
            return this.SetProperty(JsonPropertyNames.Model, value);
        }

        private static ValidationContext __CorvusValidateModel(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<BuildingOS.Shared.Entities.Dtdl.Model>().Validate(validationContext, level);
        }

        /// <summary>
        /// Tries to get the validator for the given property.
        /// </summary>
        /// <param name = "property">The property for which to get the validator.</param>
        /// <param name = "hasJsonElementBacking"><c>True</c> if the object containing the property has a JsonElement backing.</param>
        /// <param name = "propertyValidator">The validator for the property, if provided by this schema.</param>
        /// <returns><c>True</c> if the validator was found.</returns>
        private bool __TryGetCorvusLocalPropertiesValidator(in JsonObjectProperty property, bool hasJsonElementBacking, [NotNullWhen(true)] out ObjectPropertyValidator? propertyValidator)
        {
            if (hasJsonElementBacking)
            {
                if (property.NameEquals(JsonPropertyNames.ModelUtf8))
                {
                    propertyValidator = __CorvusValidateModel;
                    return true;
                }
            }
            else
            {
                if (property.NameEquals(JsonPropertyNames.Model))
                {
                    propertyValidator = __CorvusValidateModel;
                    return true;
                }
            }

            propertyValidator = null;
            return false;
        }
    }
}