//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Text.Json;
using Corvus.Json;
using Corvus.Json.Internal;

namespace BuildingOS.Shared.Entities;
public readonly partial struct Dtdl
{
    /// <summary>
    /// A type generated from a JsonSchema specification.
    /// </summary>
    public readonly partial struct DigitalTwinsFileInfo
    {
        /// <summary>
        /// The well-known property names in the JSON object.
        /// </summary>
        public static class JsonPropertyNames
        {
            /// <summary>
            /// JSON property name for <see cref = "FileVersion"/>.
            /// </summary>
            public static ReadOnlySpan<byte> FileVersionUtf8 => "fileVersion"u8;

            /// <summary>
            /// JSON property name for <see cref = "FileVersion"/>.
            /// </summary>
            public const string FileVersion = "fileVersion";
        }

        /// <summary>
        /// Gets FileVersion.
        /// </summary>
        public Corvus.Json.JsonString FileVersion
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.FileVersionUtf8, out JsonElement result))
                    {
                        return new Corvus.Json.JsonString(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.FileVersion, out JsonAny result))
                    {
                        return result.As<Corvus.Json.JsonString>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Creates an instance of a <see cref = "DigitalTwinsFileInfo"/>.
        /// </summary>
        public static DigitalTwinsFileInfo Create(Corvus.Json.JsonString fileVersion)
        {
            var builder = ImmutableList.CreateBuilder<JsonObjectProperty>();
            builder.Add(JsonPropertyNames.FileVersion, fileVersion.AsAny);
            return new(builder.ToImmutable());
        }

        /// <summary>
        /// Sets fileVersion.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public DigitalTwinsFileInfo WithFileVersion(in Corvus.Json.JsonString value)
        {
            return this.SetProperty(JsonPropertyNames.FileVersion, value);
        }

        private static ValidationContext __CorvusValidateFileVersion(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Corvus.Json.JsonString>().Validate(validationContext, level);
        }

        /// <summary>
        /// Tries to get the validator for the given property.
        /// </summary>
        /// <param name = "property">The property for which to get the validator.</param>
        /// <param name = "hasJsonElementBacking"><c>True</c> if the object containing the property has a JsonElement backing.</param>
        /// <param name = "propertyValidator">The validator for the property, if provided by this schema.</param>
        /// <returns><c>True</c> if the validator was found.</returns>
        private bool __TryGetCorvusLocalPropertiesValidator(in JsonObjectProperty property, bool hasJsonElementBacking, [NotNullWhen(true)] out ObjectPropertyValidator? propertyValidator)
        {
            if (hasJsonElementBacking)
            {
                if (property.NameEquals(JsonPropertyNames.FileVersionUtf8))
                {
                    propertyValidator = __CorvusValidateFileVersion;
                    return true;
                }
            }
            else
            {
                if (property.NameEquals(JsonPropertyNames.FileVersion))
                {
                    propertyValidator = __CorvusValidateFileVersion;
                    return true;
                }
            }

            propertyValidator = null;
            return false;
        }
    }
}