//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Text.Json;
using Corvus.Json;
using Corvus.Json.Internal;

namespace BuildingOS.Shared.Entities;
public readonly partial struct Dtdl
{
    /// <summary>
    /// A type generated from a JsonSchema specification.
    /// </summary>
    public readonly partial struct EnumValue
    {
        /// <summary>
        /// The well-known property names in the JSON object.
        /// </summary>
        public static class JsonPropertyNames
        {
            /// <summary>
            /// JSON property name for <see cref = "EnumValueValue"/>.
            /// </summary>
            public static ReadOnlySpan<byte> EnumValueValueUtf8 => "enumValue"u8;

            /// <summary>
            /// JSON property name for <see cref = "EnumValueValue"/>.
            /// </summary>
            public const string EnumValueValue = "enumValue";
            /// <summary>
            /// JSON property name for <see cref = "Name"/>.
            /// </summary>
            public static ReadOnlySpan<byte> NameUtf8 => "name"u8;

            /// <summary>
            /// JSON property name for <see cref = "Name"/>.
            /// </summary>
            public const string Name = "name";
        }

        /// <summary>
        /// Gets EnumValueValue.
        /// </summary>
        public Corvus.Json.JsonInteger EnumValueValue
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.EnumValueValueUtf8, out JsonElement result))
                    {
                        return new Corvus.Json.JsonInteger(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.EnumValueValue, out JsonAny result))
                    {
                        return result.As<Corvus.Json.JsonInteger>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets Name.
        /// </summary>
        public Corvus.Json.JsonString Name
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.NameUtf8, out JsonElement result))
                    {
                        return new Corvus.Json.JsonString(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.Name, out JsonAny result))
                    {
                        return result.As<Corvus.Json.JsonString>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Creates an instance of a <see cref = "EnumValue"/>.
        /// </summary>
        public static EnumValue Create(Corvus.Json.JsonInteger enumValueValue, Corvus.Json.JsonString name)
        {
            var builder = ImmutableList.CreateBuilder<JsonObjectProperty>();
            builder.Add(JsonPropertyNames.EnumValueValue, enumValueValue.AsAny);
            builder.Add(JsonPropertyNames.Name, name.AsAny);
            return new(builder.ToImmutable());
        }

        /// <summary>
        /// Sets enumValue.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public EnumValue WithEnumValueValue(in Corvus.Json.JsonInteger value)
        {
            return this.SetProperty(JsonPropertyNames.EnumValueValue, value);
        }

        /// <summary>
        /// Sets name.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public EnumValue WithName(in Corvus.Json.JsonString value)
        {
            return this.SetProperty(JsonPropertyNames.Name, value);
        }

        private static ValidationContext __CorvusValidateEnumValueValue(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Corvus.Json.JsonInteger>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateName(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Corvus.Json.JsonString>().Validate(validationContext, level);
        }

        /// <summary>
        /// Tries to get the validator for the given property.
        /// </summary>
        /// <param name = "property">The property for which to get the validator.</param>
        /// <param name = "hasJsonElementBacking"><c>True</c> if the object containing the property has a JsonElement backing.</param>
        /// <param name = "propertyValidator">The validator for the property, if provided by this schema.</param>
        /// <returns><c>True</c> if the validator was found.</returns>
        private bool __TryGetCorvusLocalPropertiesValidator(in JsonObjectProperty property, bool hasJsonElementBacking, [NotNullWhen(true)] out ObjectPropertyValidator? propertyValidator)
        {
            if (hasJsonElementBacking)
            {
                if (property.NameEquals(JsonPropertyNames.EnumValueValueUtf8))
                {
                    propertyValidator = __CorvusValidateEnumValueValue;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.NameUtf8))
                {
                    propertyValidator = __CorvusValidateName;
                    return true;
                }
            }
            else
            {
                if (property.NameEquals(JsonPropertyNames.EnumValueValue))
                {
                    propertyValidator = __CorvusValidateEnumValueValue;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.Name))
                {
                    propertyValidator = __CorvusValidateName;
                    return true;
                }
            }

            propertyValidator = null;
            return false;
        }
    }
}