//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Text.Json;
using Corvus.Json;
using Corvus.Json.Internal;

namespace BuildingOS.Shared.Entities;
public readonly partial struct Dtdl
{
    /// <summary>
    /// A type generated from a JsonSchema specification.
    /// </summary>
    public readonly partial struct Relationship
    {
        /// <summary>
        /// The well-known property names in the JSON object.
        /// </summary>
        public static class JsonPropertyNames
        {
            /// <summary>
            /// JSON property name for <see cref = "Etag"/>.
            /// </summary>
            public static ReadOnlySpan<byte> EtagUtf8 => "$etag"u8;

            /// <summary>
            /// JSON property name for <see cref = "Etag"/>.
            /// </summary>
            public const string Etag = "$etag";
            /// <summary>
            /// JSON property name for <see cref = "RelationshipId"/>.
            /// </summary>
            public static ReadOnlySpan<byte> RelationshipIdUtf8 => "$relationshipId"u8;

            /// <summary>
            /// JSON property name for <see cref = "RelationshipId"/>.
            /// </summary>
            public const string RelationshipId = "$relationshipId";
            /// <summary>
            /// JSON property name for <see cref = "RelationshipName"/>.
            /// </summary>
            public static ReadOnlySpan<byte> RelationshipNameUtf8 => "$relationshipName"u8;

            /// <summary>
            /// JSON property name for <see cref = "RelationshipName"/>.
            /// </summary>
            public const string RelationshipName = "$relationshipName";
            /// <summary>
            /// JSON property name for <see cref = "SourceId"/>.
            /// </summary>
            public static ReadOnlySpan<byte> SourceIdUtf8 => "$sourceId"u8;

            /// <summary>
            /// JSON property name for <see cref = "SourceId"/>.
            /// </summary>
            public const string SourceId = "$sourceId";
            /// <summary>
            /// JSON property name for <see cref = "TargetId"/>.
            /// </summary>
            public static ReadOnlySpan<byte> TargetIdUtf8 => "$targetId"u8;

            /// <summary>
            /// JSON property name for <see cref = "TargetId"/>.
            /// </summary>
            public const string TargetId = "$targetId";
        }

        /// <summary>
        /// Gets Etag.
        /// </summary>
        public Corvus.Json.JsonString Etag
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.EtagUtf8, out JsonElement result))
                    {
                        return new Corvus.Json.JsonString(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.Etag, out JsonAny result))
                    {
                        return result.As<Corvus.Json.JsonString>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets RelationshipId.
        /// </summary>
        public Corvus.Json.JsonUuid RelationshipId
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.RelationshipIdUtf8, out JsonElement result))
                    {
                        return new Corvus.Json.JsonUuid(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.RelationshipId, out JsonAny result))
                    {
                        return result.As<Corvus.Json.JsonUuid>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets RelationshipName.
        /// </summary>
        public Corvus.Json.JsonString RelationshipName
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.RelationshipNameUtf8, out JsonElement result))
                    {
                        return new Corvus.Json.JsonString(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.RelationshipName, out JsonAny result))
                    {
                        return result.As<Corvus.Json.JsonString>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets SourceId.
        /// </summary>
        public Corvus.Json.JsonString SourceId
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.SourceIdUtf8, out JsonElement result))
                    {
                        return new Corvus.Json.JsonString(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.SourceId, out JsonAny result))
                    {
                        return result.As<Corvus.Json.JsonString>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets TargetId.
        /// </summary>
        public Corvus.Json.JsonString TargetId
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.TargetIdUtf8, out JsonElement result))
                    {
                        return new Corvus.Json.JsonString(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.TargetId, out JsonAny result))
                    {
                        return result.As<Corvus.Json.JsonString>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Creates an instance of a <see cref = "Relationship"/>.
        /// </summary>
        public static Relationship Create(Corvus.Json.JsonString etag, Corvus.Json.JsonUuid relationshipId, Corvus.Json.JsonString relationshipName, Corvus.Json.JsonString sourceId, Corvus.Json.JsonString targetId)
        {
            var builder = ImmutableList.CreateBuilder<JsonObjectProperty>();
            builder.Add(JsonPropertyNames.Etag, etag.AsAny);
            builder.Add(JsonPropertyNames.RelationshipId, relationshipId.AsAny);
            builder.Add(JsonPropertyNames.RelationshipName, relationshipName.AsAny);
            builder.Add(JsonPropertyNames.SourceId, sourceId.AsAny);
            builder.Add(JsonPropertyNames.TargetId, targetId.AsAny);
            return new(builder.ToImmutable());
        }

        /// <summary>
        /// Sets $etag.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public Relationship WithEtag(in Corvus.Json.JsonString value)
        {
            return this.SetProperty(JsonPropertyNames.Etag, value);
        }

        /// <summary>
        /// Sets $relationshipId.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public Relationship WithRelationshipId(in Corvus.Json.JsonUuid value)
        {
            return this.SetProperty(JsonPropertyNames.RelationshipId, value);
        }

        /// <summary>
        /// Sets $relationshipName.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public Relationship WithRelationshipName(in Corvus.Json.JsonString value)
        {
            return this.SetProperty(JsonPropertyNames.RelationshipName, value);
        }

        /// <summary>
        /// Sets $sourceId.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public Relationship WithSourceId(in Corvus.Json.JsonString value)
        {
            return this.SetProperty(JsonPropertyNames.SourceId, value);
        }

        /// <summary>
        /// Sets $targetId.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public Relationship WithTargetId(in Corvus.Json.JsonString value)
        {
            return this.SetProperty(JsonPropertyNames.TargetId, value);
        }

        private static ValidationContext __CorvusValidateEtag(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Corvus.Json.JsonString>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateRelationshipId(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Corvus.Json.JsonUuid>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateRelationshipName(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Corvus.Json.JsonString>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateSourceId(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Corvus.Json.JsonString>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateTargetId(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Corvus.Json.JsonString>().Validate(validationContext, level);
        }

        /// <summary>
        /// Tries to get the validator for the given property.
        /// </summary>
        /// <param name = "property">The property for which to get the validator.</param>
        /// <param name = "hasJsonElementBacking"><c>True</c> if the object containing the property has a JsonElement backing.</param>
        /// <param name = "propertyValidator">The validator for the property, if provided by this schema.</param>
        /// <returns><c>True</c> if the validator was found.</returns>
        private bool __TryGetCorvusLocalPropertiesValidator(in JsonObjectProperty property, bool hasJsonElementBacking, [NotNullWhen(true)] out ObjectPropertyValidator? propertyValidator)
        {
            if (hasJsonElementBacking)
            {
                if (property.NameEquals(JsonPropertyNames.EtagUtf8))
                {
                    propertyValidator = __CorvusValidateEtag;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.RelationshipIdUtf8))
                {
                    propertyValidator = __CorvusValidateRelationshipId;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.RelationshipNameUtf8))
                {
                    propertyValidator = __CorvusValidateRelationshipName;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.SourceIdUtf8))
                {
                    propertyValidator = __CorvusValidateSourceId;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.TargetIdUtf8))
                {
                    propertyValidator = __CorvusValidateTargetId;
                    return true;
                }
            }
            else
            {
                if (property.NameEquals(JsonPropertyNames.Etag))
                {
                    propertyValidator = __CorvusValidateEtag;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.RelationshipId))
                {
                    propertyValidator = __CorvusValidateRelationshipId;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.RelationshipName))
                {
                    propertyValidator = __CorvusValidateRelationshipName;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.SourceId))
                {
                    propertyValidator = __CorvusValidateSourceId;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.TargetId))
                {
                    propertyValidator = __CorvusValidateTargetId;
                    return true;
                }
            }

            propertyValidator = null;
            return false;
        }
    }
}