//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Text.Json;
using Corvus.Json;
using Corvus.Json.Internal;

namespace BuildingOS.Shared.Entities;
public readonly partial struct Dtdl
{
    /// <summary>
    /// A type generated from a JsonSchema specification.
    /// </summary>
    public readonly partial struct ElectricDistributionPoint
    {
        /// <summary>
        /// The well-known property names in the JSON object.
        /// </summary>
        public static class JsonPropertyNames
        {
            /// <summary>
            /// JSON property name for <see cref = "Description"/>.
            /// </summary>
            public static ReadOnlySpan<byte> DescriptionUtf8 => "Description"u8;

            /// <summary>
            /// JSON property name for <see cref = "Description"/>.
            /// </summary>
            public const string Description = "Description";
            /// <summary>
            /// JSON property name for <see cref = "GlobalId"/>.
            /// </summary>
            public static ReadOnlySpan<byte> GlobalIdUtf8 => "GlobalId"u8;

            /// <summary>
            /// JSON property name for <see cref = "GlobalId"/>.
            /// </summary>
            public const string GlobalId = "GlobalId";
            /// <summary>
            /// JSON property name for <see cref = "Name"/>.
            /// </summary>
            public static ReadOnlySpan<byte> NameUtf8 => "Name"u8;

            /// <summary>
            /// JSON property name for <see cref = "Name"/>.
            /// </summary>
            public const string Name = "Name";
            /// <summary>
            /// JSON property name for <see cref = "ObjectType"/>.
            /// </summary>
            public static ReadOnlySpan<byte> ObjectTypeUtf8 => "ObjectType"u8;

            /// <summary>
            /// JSON property name for <see cref = "ObjectType"/>.
            /// </summary>
            public const string ObjectType = "ObjectType";
            /// <summary>
            /// JSON property name for <see cref = "PredefinedType"/>.
            /// </summary>
            public static ReadOnlySpan<byte> PredefinedTypeUtf8 => "PredefinedType"u8;

            /// <summary>
            /// JSON property name for <see cref = "PredefinedType"/>.
            /// </summary>
            public const string PredefinedType = "PredefinedType";
            /// <summary>
            /// JSON property name for <see cref = "Tag"/>.
            /// </summary>
            public static ReadOnlySpan<byte> TagUtf8 => "Tag"u8;

            /// <summary>
            /// JSON property name for <see cref = "Tag"/>.
            /// </summary>
            public const string Tag = "Tag";
        }

        /// <summary>
        /// Gets Description.
        /// </summary>
        public Corvus.Json.JsonString Description
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.DescriptionUtf8, out JsonElement result))
                    {
                        return new Corvus.Json.JsonString(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.Description, out JsonAny result))
                    {
                        return result.As<Corvus.Json.JsonString>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets GlobalId.
        /// </summary>
        public Corvus.Json.JsonString GlobalId
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.GlobalIdUtf8, out JsonElement result))
                    {
                        return new Corvus.Json.JsonString(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.GlobalId, out JsonAny result))
                    {
                        return result.As<Corvus.Json.JsonString>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets Name.
        /// </summary>
        public Corvus.Json.JsonString Name
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.NameUtf8, out JsonElement result))
                    {
                        return new Corvus.Json.JsonString(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.Name, out JsonAny result))
                    {
                        return result.As<Corvus.Json.JsonString>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets ObjectType.
        /// </summary>
        public Corvus.Json.JsonString ObjectType
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.ObjectTypeUtf8, out JsonElement result))
                    {
                        return new Corvus.Json.JsonString(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.ObjectType, out JsonAny result))
                    {
                        return result.As<Corvus.Json.JsonString>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets PredefinedType.
        /// </summary>
        public Corvus.Json.JsonString PredefinedType
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.PredefinedTypeUtf8, out JsonElement result))
                    {
                        return new Corvus.Json.JsonString(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.PredefinedType, out JsonAny result))
                    {
                        return result.As<Corvus.Json.JsonString>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets Tag.
        /// </summary>
        public Corvus.Json.JsonString Tag
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.TagUtf8, out JsonElement result))
                    {
                        return new Corvus.Json.JsonString(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.Tag, out JsonAny result))
                    {
                        return result.As<Corvus.Json.JsonString>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Creates an instance of a <see cref = "ElectricDistributionPoint"/>.
        /// </summary>
        public static ElectricDistributionPoint Create(Corvus.Json.JsonString description, Corvus.Json.JsonString globalId, Corvus.Json.JsonString name, Corvus.Json.JsonString objectType, Corvus.Json.JsonString tag, Corvus.Json.JsonString? predefinedType = null)
        {
            var builder = ImmutableList.CreateBuilder<JsonObjectProperty>();
            builder.Add(JsonPropertyNames.Description, description.AsAny);
            builder.Add(JsonPropertyNames.GlobalId, globalId.AsAny);
            builder.Add(JsonPropertyNames.Name, name.AsAny);
            builder.Add(JsonPropertyNames.ObjectType, objectType.AsAny);
            builder.Add(JsonPropertyNames.Tag, tag.AsAny);
            if (predefinedType is Corvus.Json.JsonString predefinedType__)
            {
                builder.Add(JsonPropertyNames.PredefinedType, predefinedType__.AsAny);
            }

            return new(builder.ToImmutable());
        }

        /// <summary>
        /// Sets Description.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public ElectricDistributionPoint WithDescription(in Corvus.Json.JsonString value)
        {
            return this.SetProperty(JsonPropertyNames.Description, value);
        }

        /// <summary>
        /// Sets GlobalId.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public ElectricDistributionPoint WithGlobalId(in Corvus.Json.JsonString value)
        {
            return this.SetProperty(JsonPropertyNames.GlobalId, value);
        }

        /// <summary>
        /// Sets Name.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public ElectricDistributionPoint WithName(in Corvus.Json.JsonString value)
        {
            return this.SetProperty(JsonPropertyNames.Name, value);
        }

        /// <summary>
        /// Sets ObjectType.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public ElectricDistributionPoint WithObjectType(in Corvus.Json.JsonString value)
        {
            return this.SetProperty(JsonPropertyNames.ObjectType, value);
        }

        /// <summary>
        /// Sets PredefinedType.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public ElectricDistributionPoint WithPredefinedType(in Corvus.Json.JsonString value)
        {
            return this.SetProperty(JsonPropertyNames.PredefinedType, value);
        }

        /// <summary>
        /// Sets Tag.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public ElectricDistributionPoint WithTag(in Corvus.Json.JsonString value)
        {
            return this.SetProperty(JsonPropertyNames.Tag, value);
        }

        private static ValidationContext __CorvusValidateDescription(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Corvus.Json.JsonString>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateGlobalId(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Corvus.Json.JsonString>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateName(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Corvus.Json.JsonString>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateObjectType(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Corvus.Json.JsonString>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateTag(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Corvus.Json.JsonString>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidatePredefinedType(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Corvus.Json.JsonString>().Validate(validationContext, level);
        }

        /// <summary>
        /// Tries to get the validator for the given property.
        /// </summary>
        /// <param name = "property">The property for which to get the validator.</param>
        /// <param name = "hasJsonElementBacking"><c>True</c> if the object containing the property has a JsonElement backing.</param>
        /// <param name = "propertyValidator">The validator for the property, if provided by this schema.</param>
        /// <returns><c>True</c> if the validator was found.</returns>
        private bool __TryGetCorvusLocalPropertiesValidator(in JsonObjectProperty property, bool hasJsonElementBacking, [NotNullWhen(true)] out ObjectPropertyValidator? propertyValidator)
        {
            if (hasJsonElementBacking)
            {
                if (property.NameEquals(JsonPropertyNames.DescriptionUtf8))
                {
                    propertyValidator = __CorvusValidateDescription;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.GlobalIdUtf8))
                {
                    propertyValidator = __CorvusValidateGlobalId;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.NameUtf8))
                {
                    propertyValidator = __CorvusValidateName;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.ObjectTypeUtf8))
                {
                    propertyValidator = __CorvusValidateObjectType;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.TagUtf8))
                {
                    propertyValidator = __CorvusValidateTag;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.PredefinedTypeUtf8))
                {
                    propertyValidator = __CorvusValidatePredefinedType;
                    return true;
                }
            }
            else
            {
                if (property.NameEquals(JsonPropertyNames.Description))
                {
                    propertyValidator = __CorvusValidateDescription;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.GlobalId))
                {
                    propertyValidator = __CorvusValidateGlobalId;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.Name))
                {
                    propertyValidator = __CorvusValidateName;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.ObjectType))
                {
                    propertyValidator = __CorvusValidateObjectType;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.Tag))
                {
                    propertyValidator = __CorvusValidateTag;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.PredefinedType))
                {
                    propertyValidator = __CorvusValidatePredefinedType;
                    return true;
                }
            }

            propertyValidator = null;
            return false;
        }
    }
}