//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Text.Json;
using Corvus.Json;
using Corvus.Json.Internal;

namespace BuildingOS.Shared.Entities;
public readonly partial struct Dtdl
{
    /// <summary>
    /// A type generated from a JsonSchema specification.
    /// </summary>
    public readonly partial struct DigitalTwinsModel
    {
        /// <summary>
        /// The well-known property names in the JSON object.
        /// </summary>
        public static class JsonPropertyNames
        {
            /// <summary>
            /// JSON property name for <see cref = "Contents"/>.
            /// </summary>
            public static ReadOnlySpan<byte> ContentsUtf8 => "contents"u8;

            /// <summary>
            /// JSON property name for <see cref = "Contents"/>.
            /// </summary>
            public const string Contents = "contents";
            /// <summary>
            /// JSON property name for <see cref = "Context"/>.
            /// </summary>
            public static ReadOnlySpan<byte> ContextUtf8 => "@context"u8;

            /// <summary>
            /// JSON property name for <see cref = "Context"/>.
            /// </summary>
            public const string Context = "@context";
            /// <summary>
            /// JSON property name for <see cref = "DisplayName"/>.
            /// </summary>
            public static ReadOnlySpan<byte> DisplayNameUtf8 => "displayName"u8;

            /// <summary>
            /// JSON property name for <see cref = "DisplayName"/>.
            /// </summary>
            public const string DisplayName = "displayName";
            /// <summary>
            /// JSON property name for <see cref = "Extends"/>.
            /// </summary>
            public static ReadOnlySpan<byte> ExtendsUtf8 => "extends"u8;

            /// <summary>
            /// JSON property name for <see cref = "Extends"/>.
            /// </summary>
            public const string Extends = "extends";
            /// <summary>
            /// JSON property name for <see cref = "Id"/>.
            /// </summary>
            public static ReadOnlySpan<byte> IdUtf8 => "@id"u8;

            /// <summary>
            /// JSON property name for <see cref = "Id"/>.
            /// </summary>
            public const string Id = "@id";
            /// <summary>
            /// JSON property name for <see cref = "Type"/>.
            /// </summary>
            public static ReadOnlySpan<byte> TypeUtf8 => "@type"u8;

            /// <summary>
            /// JSON property name for <see cref = "Type"/>.
            /// </summary>
            public const string Type = "@type";
        }

        /// <summary>
        /// Gets Contents.
        /// </summary>
        public BuildingOS.Shared.Entities.Dtdl.DigitalTwinsModel.ContentArray Contents
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.ContentsUtf8, out JsonElement result))
                    {
                        return new BuildingOS.Shared.Entities.Dtdl.DigitalTwinsModel.ContentArray(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.Contents, out JsonAny result))
                    {
                        return result.As<BuildingOS.Shared.Entities.Dtdl.DigitalTwinsModel.ContentArray>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets Context.
        /// </summary>
        public Corvus.Json.JsonString Context
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.ContextUtf8, out JsonElement result))
                    {
                        return new Corvus.Json.JsonString(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.Context, out JsonAny result))
                    {
                        return result.As<Corvus.Json.JsonString>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets DisplayName.
        /// </summary>
        public Corvus.Json.JsonString DisplayName
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.DisplayNameUtf8, out JsonElement result))
                    {
                        return new Corvus.Json.JsonString(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.DisplayName, out JsonAny result))
                    {
                        return result.As<Corvus.Json.JsonString>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets Extends.
        /// </summary>
        public BuildingOS.Shared.Entities.Dtdl.DigitalTwinsModel.JsonStringArray Extends
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.ExtendsUtf8, out JsonElement result))
                    {
                        return new BuildingOS.Shared.Entities.Dtdl.DigitalTwinsModel.JsonStringArray(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.Extends, out JsonAny result))
                    {
                        return result.As<BuildingOS.Shared.Entities.Dtdl.DigitalTwinsModel.JsonStringArray>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets Id.
        /// </summary>
        public Corvus.Json.JsonString Id
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.IdUtf8, out JsonElement result))
                    {
                        return new Corvus.Json.JsonString(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.Id, out JsonAny result))
                    {
                        return result.As<Corvus.Json.JsonString>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets Type.
        /// </summary>
        public Corvus.Json.JsonString Type
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.TypeUtf8, out JsonElement result))
                    {
                        return new Corvus.Json.JsonString(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.Type, out JsonAny result))
                    {
                        return result.As<Corvus.Json.JsonString>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Creates an instance of a <see cref = "DigitalTwinsModel"/>.
        /// </summary>
        public static DigitalTwinsModel Create(Corvus.Json.JsonString context, Corvus.Json.JsonString displayName, Corvus.Json.JsonString id, Corvus.Json.JsonString type, BuildingOS.Shared.Entities.Dtdl.DigitalTwinsModel.ContentArray? contents = null, BuildingOS.Shared.Entities.Dtdl.DigitalTwinsModel.JsonStringArray? extends = null)
        {
            var builder = ImmutableList.CreateBuilder<JsonObjectProperty>();
            builder.Add(JsonPropertyNames.Context, context.AsAny);
            builder.Add(JsonPropertyNames.DisplayName, displayName.AsAny);
            builder.Add(JsonPropertyNames.Id, id.AsAny);
            builder.Add(JsonPropertyNames.Type, type.AsAny);
            if (contents is BuildingOS.Shared.Entities.Dtdl.DigitalTwinsModel.ContentArray contents__)
            {
                builder.Add(JsonPropertyNames.Contents, contents__.AsAny);
            }

            if (extends is BuildingOS.Shared.Entities.Dtdl.DigitalTwinsModel.JsonStringArray extends__)
            {
                builder.Add(JsonPropertyNames.Extends, extends__.AsAny);
            }

            return new(builder.ToImmutable());
        }

        /// <summary>
        /// Sets contents.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public DigitalTwinsModel WithContents(in BuildingOS.Shared.Entities.Dtdl.DigitalTwinsModel.ContentArray value)
        {
            return this.SetProperty(JsonPropertyNames.Contents, value);
        }

        /// <summary>
        /// Sets @context.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public DigitalTwinsModel WithContext(in Corvus.Json.JsonString value)
        {
            return this.SetProperty(JsonPropertyNames.Context, value);
        }

        /// <summary>
        /// Sets displayName.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public DigitalTwinsModel WithDisplayName(in Corvus.Json.JsonString value)
        {
            return this.SetProperty(JsonPropertyNames.DisplayName, value);
        }

        /// <summary>
        /// Sets extends.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public DigitalTwinsModel WithExtends(in BuildingOS.Shared.Entities.Dtdl.DigitalTwinsModel.JsonStringArray value)
        {
            return this.SetProperty(JsonPropertyNames.Extends, value);
        }

        /// <summary>
        /// Sets @id.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public DigitalTwinsModel WithId(in Corvus.Json.JsonString value)
        {
            return this.SetProperty(JsonPropertyNames.Id, value);
        }

        /// <summary>
        /// Sets @type.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public DigitalTwinsModel WithType(in Corvus.Json.JsonString value)
        {
            return this.SetProperty(JsonPropertyNames.Type, value);
        }

        private static ValidationContext __CorvusValidateContext(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Corvus.Json.JsonString>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateId(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Corvus.Json.JsonString>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateType(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Corvus.Json.JsonString>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateDisplayName(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Corvus.Json.JsonString>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateContents(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<BuildingOS.Shared.Entities.Dtdl.DigitalTwinsModel.ContentArray>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateExtends(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<BuildingOS.Shared.Entities.Dtdl.DigitalTwinsModel.JsonStringArray>().Validate(validationContext, level);
        }

        /// <summary>
        /// Tries to get the validator for the given property.
        /// </summary>
        /// <param name = "property">The property for which to get the validator.</param>
        /// <param name = "hasJsonElementBacking"><c>True</c> if the object containing the property has a JsonElement backing.</param>
        /// <param name = "propertyValidator">The validator for the property, if provided by this schema.</param>
        /// <returns><c>True</c> if the validator was found.</returns>
        private bool __TryGetCorvusLocalPropertiesValidator(in JsonObjectProperty property, bool hasJsonElementBacking, [NotNullWhen(true)] out ObjectPropertyValidator? propertyValidator)
        {
            if (hasJsonElementBacking)
            {
                if (property.NameEquals(JsonPropertyNames.ContextUtf8))
                {
                    propertyValidator = __CorvusValidateContext;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.IdUtf8))
                {
                    propertyValidator = __CorvusValidateId;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.TypeUtf8))
                {
                    propertyValidator = __CorvusValidateType;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.DisplayNameUtf8))
                {
                    propertyValidator = __CorvusValidateDisplayName;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.ContentsUtf8))
                {
                    propertyValidator = __CorvusValidateContents;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.ExtendsUtf8))
                {
                    propertyValidator = __CorvusValidateExtends;
                    return true;
                }
            }
            else
            {
                if (property.NameEquals(JsonPropertyNames.Context))
                {
                    propertyValidator = __CorvusValidateContext;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.Id))
                {
                    propertyValidator = __CorvusValidateId;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.Type))
                {
                    propertyValidator = __CorvusValidateType;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.DisplayName))
                {
                    propertyValidator = __CorvusValidateDisplayName;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.Contents))
                {
                    propertyValidator = __CorvusValidateContents;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.Extends))
                {
                    propertyValidator = __CorvusValidateExtends;
                    return true;
                }
            }

            propertyValidator = null;
            return false;
        }
    }
}