//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Text.Json;
using Corvus.Json;
using Corvus.Json.Internal;

namespace BuildingOS.Shared.Entities;
/// <summary>
/// A type generated from a JsonSchema specification.
/// </summary>
public readonly partial struct ElectricDeviceMessageJson
{
    /// <summary>
    /// The well-known property names in the JSON object.
    /// </summary>
    public static class JsonPropertyNames
    {
        /// <summary>
        /// JSON property name for <see cref = "AcqTime"/>.
        /// </summary>
        public static ReadOnlySpan<byte> AcqTimeUtf8 => "acqTime"u8;

        /// <summary>
        /// JSON property name for <see cref = "AcqTime"/>.
        /// </summary>
        public const string AcqTime = "acqTime";
        /// <summary>
        /// JSON property name for <see cref = "ConnTime"/>.
        /// </summary>
        public static ReadOnlySpan<byte> ConnTimeUtf8 => "connTime"u8;

        /// <summary>
        /// JSON property name for <see cref = "ConnTime"/>.
        /// </summary>
        public const string ConnTime = "connTime";
        /// <summary>
        /// JSON property name for <see cref = "DeviceId"/>.
        /// </summary>
        public static ReadOnlySpan<byte> DeviceIdUtf8 => "deviceId"u8;

        /// <summary>
        /// JSON property name for <see cref = "DeviceId"/>.
        /// </summary>
        public const string DeviceId = "deviceId";
        /// <summary>
        /// JSON property name for <see cref = "TelemetryData"/>.
        /// </summary>
        public static ReadOnlySpan<byte> TelemetryDataUtf8 => "telemetryData"u8;

        /// <summary>
        /// JSON property name for <see cref = "TelemetryData"/>.
        /// </summary>
        public const string TelemetryData = "telemetryData";
    }

    /// <summary>
    /// Gets AcqTime.
    /// </summary>
    public Corvus.Json.JsonString AcqTime
    {
        get
        {
            if ((this.backing & Backing.JsonElement) != 0)
            {
                if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                {
                    return default;
                }

                if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.AcqTimeUtf8, out JsonElement result))
                {
                    return new Corvus.Json.JsonString(result);
                }
            }

            if ((this.backing & Backing.Object) != 0)
            {
                if (this.objectBacking.TryGetValue(JsonPropertyNames.AcqTime, out JsonAny result))
                {
                    return result.As<Corvus.Json.JsonString>();
                }
            }

            return default;
        }
    }

    /// <summary>
    /// Gets ConnTime.
    /// </summary>
    public Corvus.Json.JsonString ConnTime
    {
        get
        {
            if ((this.backing & Backing.JsonElement) != 0)
            {
                if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                {
                    return default;
                }

                if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.ConnTimeUtf8, out JsonElement result))
                {
                    return new Corvus.Json.JsonString(result);
                }
            }

            if ((this.backing & Backing.Object) != 0)
            {
                if (this.objectBacking.TryGetValue(JsonPropertyNames.ConnTime, out JsonAny result))
                {
                    return result.As<Corvus.Json.JsonString>();
                }
            }

            return default;
        }
    }

    /// <summary>
    /// Gets DeviceId.
    /// </summary>
    public Corvus.Json.JsonString DeviceId
    {
        get
        {
            if ((this.backing & Backing.JsonElement) != 0)
            {
                if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                {
                    return default;
                }

                if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.DeviceIdUtf8, out JsonElement result))
                {
                    return new Corvus.Json.JsonString(result);
                }
            }

            if ((this.backing & Backing.Object) != 0)
            {
                if (this.objectBacking.TryGetValue(JsonPropertyNames.DeviceId, out JsonAny result))
                {
                    return result.As<Corvus.Json.JsonString>();
                }
            }

            return default;
        }
    }

    /// <summary>
    /// Gets TelemetryData.
    /// </summary>
    public BuildingOS.Shared.Entities.ElectricDeviceMessageJson.ElectricDeviceTelemetryEntityArray TelemetryData
    {
        get
        {
            if ((this.backing & Backing.JsonElement) != 0)
            {
                if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                {
                    return default;
                }

                if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.TelemetryDataUtf8, out JsonElement result))
                {
                    return new BuildingOS.Shared.Entities.ElectricDeviceMessageJson.ElectricDeviceTelemetryEntityArray(result);
                }
            }

            if ((this.backing & Backing.Object) != 0)
            {
                if (this.objectBacking.TryGetValue(JsonPropertyNames.TelemetryData, out JsonAny result))
                {
                    return result.As<BuildingOS.Shared.Entities.ElectricDeviceMessageJson.ElectricDeviceTelemetryEntityArray>();
                }
            }

            return default;
        }
    }

    /// <summary>
    /// Creates an instance of a <see cref = "ElectricDeviceMessageJson"/>.
    /// </summary>
    public static ElectricDeviceMessageJson Create(Corvus.Json.JsonString acqTime, Corvus.Json.JsonString connTime, BuildingOS.Shared.Entities.ElectricDeviceMessageJson.ElectricDeviceTelemetryEntityArray telemetryData, Corvus.Json.JsonString? deviceId = null)
    {
        var builder = ImmutableList.CreateBuilder<JsonObjectProperty>();
        builder.Add(JsonPropertyNames.AcqTime, acqTime.AsAny);
        builder.Add(JsonPropertyNames.ConnTime, connTime.AsAny);
        builder.Add(JsonPropertyNames.TelemetryData, telemetryData.AsAny);
        if (deviceId is Corvus.Json.JsonString deviceId__)
        {
            builder.Add(JsonPropertyNames.DeviceId, deviceId__.AsAny);
        }

        return new(builder.ToImmutable());
    }

    /// <summary>
    /// Sets acqTime.
    /// </summary>
    /// <param name = "value">The value to set.</param>
    /// <returns>The entity with the updated property.</returns>
    public ElectricDeviceMessageJson WithAcqTime(in Corvus.Json.JsonString value)
    {
        return this.SetProperty(JsonPropertyNames.AcqTime, value);
    }

    /// <summary>
    /// Sets connTime.
    /// </summary>
    /// <param name = "value">The value to set.</param>
    /// <returns>The entity with the updated property.</returns>
    public ElectricDeviceMessageJson WithConnTime(in Corvus.Json.JsonString value)
    {
        return this.SetProperty(JsonPropertyNames.ConnTime, value);
    }

    /// <summary>
    /// Sets deviceId.
    /// </summary>
    /// <param name = "value">The value to set.</param>
    /// <returns>The entity with the updated property.</returns>
    public ElectricDeviceMessageJson WithDeviceId(in Corvus.Json.JsonString value)
    {
        return this.SetProperty(JsonPropertyNames.DeviceId, value);
    }

    /// <summary>
    /// Sets telemetryData.
    /// </summary>
    /// <param name = "value">The value to set.</param>
    /// <returns>The entity with the updated property.</returns>
    public ElectricDeviceMessageJson WithTelemetryData(in BuildingOS.Shared.Entities.ElectricDeviceMessageJson.ElectricDeviceTelemetryEntityArray value)
    {
        return this.SetProperty(JsonPropertyNames.TelemetryData, value);
    }

    private static ValidationContext __CorvusValidateTelemetryData(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
    {
        return property.ValueAs<BuildingOS.Shared.Entities.ElectricDeviceMessageJson.ElectricDeviceTelemetryEntityArray>().Validate(validationContext, level);
    }

    private static ValidationContext __CorvusValidateConnTime(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
    {
        return property.ValueAs<Corvus.Json.JsonString>().Validate(validationContext, level);
    }

    private static ValidationContext __CorvusValidateAcqTime(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
    {
        return property.ValueAs<Corvus.Json.JsonString>().Validate(validationContext, level);
    }

    private static ValidationContext __CorvusValidateDeviceId(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
    {
        return property.ValueAs<Corvus.Json.JsonString>().Validate(validationContext, level);
    }

    /// <summary>
    /// Tries to get the validator for the given property.
    /// </summary>
    /// <param name = "property">The property for which to get the validator.</param>
    /// <param name = "hasJsonElementBacking"><c>True</c> if the object containing the property has a JsonElement backing.</param>
    /// <param name = "propertyValidator">The validator for the property, if provided by this schema.</param>
    /// <returns><c>True</c> if the validator was found.</returns>
    private bool __TryGetCorvusLocalPropertiesValidator(in JsonObjectProperty property, bool hasJsonElementBacking, [NotNullWhen(true)] out ObjectPropertyValidator? propertyValidator)
    {
        if (hasJsonElementBacking)
        {
            if (property.NameEquals(JsonPropertyNames.TelemetryDataUtf8))
            {
                propertyValidator = __CorvusValidateTelemetryData;
                return true;
            }
            else if (property.NameEquals(JsonPropertyNames.ConnTimeUtf8))
            {
                propertyValidator = __CorvusValidateConnTime;
                return true;
            }
            else if (property.NameEquals(JsonPropertyNames.AcqTimeUtf8))
            {
                propertyValidator = __CorvusValidateAcqTime;
                return true;
            }
            else if (property.NameEquals(JsonPropertyNames.DeviceIdUtf8))
            {
                propertyValidator = __CorvusValidateDeviceId;
                return true;
            }
        }
        else
        {
            if (property.NameEquals(JsonPropertyNames.TelemetryData))
            {
                propertyValidator = __CorvusValidateTelemetryData;
                return true;
            }
            else if (property.NameEquals(JsonPropertyNames.ConnTime))
            {
                propertyValidator = __CorvusValidateConnTime;
                return true;
            }
            else if (property.NameEquals(JsonPropertyNames.AcqTime))
            {
                propertyValidator = __CorvusValidateAcqTime;
                return true;
            }
            else if (property.NameEquals(JsonPropertyNames.DeviceId))
            {
                propertyValidator = __CorvusValidateDeviceId;
                return true;
            }
        }

        propertyValidator = null;
        return false;
    }
}