//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Text.Json;
using Corvus.Json;
using Corvus.Json.Internal;

namespace BuildingOS.Shared.Entities;
public readonly partial struct EnvironmentalDeviceMessageJson
{
    public readonly partial struct EnvironmentalDeviceTelemetryEntity
    {
        /// <summary>
        /// A type generated from a JsonSchema specification.
        /// </summary>
        public readonly partial struct OneOf0Entity
        {
            /// <summary>
            /// The well-known property names in the JSON object.
            /// </summary>
            public static class JsonPropertyNames
            {
                /// <summary>
                /// JSON property name for <see cref = "Type"/>.
                /// </summary>
                public static ReadOnlySpan<byte> TypeUtf8 => "type"u8;

                /// <summary>
                /// JSON property name for <see cref = "Type"/>.
                /// </summary>
                public const string Type = "type";
            }

            /// <summary>
            /// Gets Type.
            /// </summary>
            public BuildingOS.Shared.Entities.EnvironmentalDeviceMessageJson.EnvironmentalDeviceTelemetryEntity.OneOf0Entity.TypeEntity Type
            {
                get
                {
                    if ((this.backing & Backing.JsonElement) != 0)
                    {
                        if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                        {
                            return default;
                        }

                        if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.TypeUtf8, out JsonElement result))
                        {
                            return new BuildingOS.Shared.Entities.EnvironmentalDeviceMessageJson.EnvironmentalDeviceTelemetryEntity.OneOf0Entity.TypeEntity(result);
                        }
                    }

                    if ((this.backing & Backing.Object) != 0)
                    {
                        if (this.objectBacking.TryGetValue(JsonPropertyNames.Type, out JsonAny result))
                        {
                            return result.As<BuildingOS.Shared.Entities.EnvironmentalDeviceMessageJson.EnvironmentalDeviceTelemetryEntity.OneOf0Entity.TypeEntity>();
                        }
                    }

                    return default;
                }
            }

            /// <summary>
            /// Creates an instance of a <see cref = "OneOf0Entity"/>.
            /// </summary>
            public static OneOf0Entity Create(BuildingOS.Shared.Entities.EnvironmentalDeviceMessageJson.EnvironmentalDeviceTelemetryEntity.OneOf0Entity.TypeEntity? type = null)
            {
                var builder = ImmutableList.CreateBuilder<JsonObjectProperty>();
                if (type is BuildingOS.Shared.Entities.EnvironmentalDeviceMessageJson.EnvironmentalDeviceTelemetryEntity.OneOf0Entity.TypeEntity type__)
                {
                    builder.Add(JsonPropertyNames.Type, type__.AsAny);
                }

                return new(builder.ToImmutable());
            }

            private static ValidationContext __CorvusValidateType(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
            {
                return property.ValueAs<BuildingOS.Shared.Entities.EnvironmentalDeviceMessageJson.EnvironmentalDeviceTelemetryEntity.OneOf0Entity.TypeEntity>().Validate(validationContext, level);
            }

            /// <summary>
            /// Tries to get the validator for the given property.
            /// </summary>
            /// <param name = "property">The property for which to get the validator.</param>
            /// <param name = "hasJsonElementBacking"><c>True</c> if the object containing the property has a JsonElement backing.</param>
            /// <param name = "propertyValidator">The validator for the property, if provided by this schema.</param>
            /// <returns><c>True</c> if the validator was found.</returns>
            private bool __TryGetCorvusLocalPropertiesValidator(in JsonObjectProperty property, bool hasJsonElementBacking, [NotNullWhen(true)] out ObjectPropertyValidator? propertyValidator)
            {
                if (hasJsonElementBacking)
                {
                    if (property.NameEquals(JsonPropertyNames.TypeUtf8))
                    {
                        propertyValidator = __CorvusValidateType;
                        return true;
                    }
                }
                else
                {
                    if (property.NameEquals(JsonPropertyNames.Type))
                    {
                        propertyValidator = __CorvusValidateType;
                        return true;
                    }
                }

                propertyValidator = null;
                return false;
            }
        }
    }
}