//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Text.Json;
using Corvus.Json;
using Corvus.Json.Internal;

namespace BuildingOS.Shared.Entities;
/// <summary>
/// A type generated from a JsonSchema specification.
/// </summary>
public readonly partial struct EnvironmentalDeviceMessageJson
{
    /// <summary>
    /// The well-known property names in the JSON object.
    /// </summary>
    public static class JsonPropertyNames
    {
        /// <summary>
        /// JSON property name for <see cref = "Gateway"/>.
        /// </summary>
        public static ReadOnlySpan<byte> GatewayUtf8 => "gateway"u8;

        /// <summary>
        /// JSON property name for <see cref = "Gateway"/>.
        /// </summary>
        public const string Gateway = "gateway";
        /// <summary>
        /// JSON property name for <see cref = "Logtimestamp"/>.
        /// </summary>
        public static ReadOnlySpan<byte> LogtimestampUtf8 => "logtimestamp"u8;

        /// <summary>
        /// JSON property name for <see cref = "Logtimestamp"/>.
        /// </summary>
        public const string Logtimestamp = "logtimestamp";
        /// <summary>
        /// JSON property name for <see cref = "Sensors"/>.
        /// </summary>
        public static ReadOnlySpan<byte> SensorsUtf8 => "sensors"u8;

        /// <summary>
        /// JSON property name for <see cref = "Sensors"/>.
        /// </summary>
        public const string Sensors = "sensors";
    }

    /// <summary>
    /// Gets Gateway.
    /// </summary>
    public Corvus.Json.JsonString Gateway
    {
        get
        {
            if ((this.backing & Backing.JsonElement) != 0)
            {
                if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                {
                    return default;
                }

                if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.GatewayUtf8, out JsonElement result))
                {
                    return new Corvus.Json.JsonString(result);
                }
            }

            if ((this.backing & Backing.Object) != 0)
            {
                if (this.objectBacking.TryGetValue(JsonPropertyNames.Gateway, out JsonAny result))
                {
                    return result.As<Corvus.Json.JsonString>();
                }
            }

            return default;
        }
    }

    /// <summary>
    /// Gets Logtimestamp.
    /// </summary>
    public Corvus.Json.JsonDateTime Logtimestamp
    {
        get
        {
            if ((this.backing & Backing.JsonElement) != 0)
            {
                if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                {
                    return default;
                }

                if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.LogtimestampUtf8, out JsonElement result))
                {
                    return new Corvus.Json.JsonDateTime(result);
                }
            }

            if ((this.backing & Backing.Object) != 0)
            {
                if (this.objectBacking.TryGetValue(JsonPropertyNames.Logtimestamp, out JsonAny result))
                {
                    return result.As<Corvus.Json.JsonDateTime>();
                }
            }

            return default;
        }
    }

    /// <summary>
    /// Gets Sensors.
    /// </summary>
    public BuildingOS.Shared.Entities.EnvironmentalDeviceMessageJson.EnvironmentalDeviceTelemetryEntityArray Sensors
    {
        get
        {
            if ((this.backing & Backing.JsonElement) != 0)
            {
                if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                {
                    return default;
                }

                if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.SensorsUtf8, out JsonElement result))
                {
                    return new BuildingOS.Shared.Entities.EnvironmentalDeviceMessageJson.EnvironmentalDeviceTelemetryEntityArray(result);
                }
            }

            if ((this.backing & Backing.Object) != 0)
            {
                if (this.objectBacking.TryGetValue(JsonPropertyNames.Sensors, out JsonAny result))
                {
                    return result.As<BuildingOS.Shared.Entities.EnvironmentalDeviceMessageJson.EnvironmentalDeviceTelemetryEntityArray>();
                }
            }

            return default;
        }
    }

    /// <summary>
    /// Creates an instance of a <see cref = "EnvironmentalDeviceMessageJson"/>.
    /// </summary>
    public static EnvironmentalDeviceMessageJson Create(Corvus.Json.JsonString gateway, Corvus.Json.JsonDateTime logtimestamp, BuildingOS.Shared.Entities.EnvironmentalDeviceMessageJson.EnvironmentalDeviceTelemetryEntityArray sensors)
    {
        var builder = ImmutableList.CreateBuilder<JsonObjectProperty>();
        builder.Add(JsonPropertyNames.Gateway, gateway.AsAny);
        builder.Add(JsonPropertyNames.Logtimestamp, logtimestamp.AsAny);
        builder.Add(JsonPropertyNames.Sensors, sensors.AsAny);
        return new(builder.ToImmutable());
    }

    /// <summary>
    /// Sets gateway.
    /// </summary>
    /// <param name = "value">The value to set.</param>
    /// <returns>The entity with the updated property.</returns>
    public EnvironmentalDeviceMessageJson WithGateway(in Corvus.Json.JsonString value)
    {
        return this.SetProperty(JsonPropertyNames.Gateway, value);
    }

    /// <summary>
    /// Sets logtimestamp.
    /// </summary>
    /// <param name = "value">The value to set.</param>
    /// <returns>The entity with the updated property.</returns>
    public EnvironmentalDeviceMessageJson WithLogtimestamp(in Corvus.Json.JsonDateTime value)
    {
        return this.SetProperty(JsonPropertyNames.Logtimestamp, value);
    }

    /// <summary>
    /// Sets sensors.
    /// </summary>
    /// <param name = "value">The value to set.</param>
    /// <returns>The entity with the updated property.</returns>
    public EnvironmentalDeviceMessageJson WithSensors(in BuildingOS.Shared.Entities.EnvironmentalDeviceMessageJson.EnvironmentalDeviceTelemetryEntityArray value)
    {
        return this.SetProperty(JsonPropertyNames.Sensors, value);
    }

    private static ValidationContext __CorvusValidateLogtimestamp(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
    {
        return property.ValueAs<Corvus.Json.JsonDateTime>().Validate(validationContext, level);
    }

    private static ValidationContext __CorvusValidateGateway(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
    {
        return property.ValueAs<Corvus.Json.JsonString>().Validate(validationContext, level);
    }

    private static ValidationContext __CorvusValidateSensors(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
    {
        return property.ValueAs<BuildingOS.Shared.Entities.EnvironmentalDeviceMessageJson.EnvironmentalDeviceTelemetryEntityArray>().Validate(validationContext, level);
    }

    /// <summary>
    /// Tries to get the validator for the given property.
    /// </summary>
    /// <param name = "property">The property for which to get the validator.</param>
    /// <param name = "hasJsonElementBacking"><c>True</c> if the object containing the property has a JsonElement backing.</param>
    /// <param name = "propertyValidator">The validator for the property, if provided by this schema.</param>
    /// <returns><c>True</c> if the validator was found.</returns>
    private bool __TryGetCorvusLocalPropertiesValidator(in JsonObjectProperty property, bool hasJsonElementBacking, [NotNullWhen(true)] out ObjectPropertyValidator? propertyValidator)
    {
        if (hasJsonElementBacking)
        {
            if (property.NameEquals(JsonPropertyNames.LogtimestampUtf8))
            {
                propertyValidator = __CorvusValidateLogtimestamp;
                return true;
            }
            else if (property.NameEquals(JsonPropertyNames.GatewayUtf8))
            {
                propertyValidator = __CorvusValidateGateway;
                return true;
            }
            else if (property.NameEquals(JsonPropertyNames.SensorsUtf8))
            {
                propertyValidator = __CorvusValidateSensors;
                return true;
            }
        }
        else
        {
            if (property.NameEquals(JsonPropertyNames.Logtimestamp))
            {
                propertyValidator = __CorvusValidateLogtimestamp;
                return true;
            }
            else if (property.NameEquals(JsonPropertyNames.Gateway))
            {
                propertyValidator = __CorvusValidateGateway;
                return true;
            }
            else if (property.NameEquals(JsonPropertyNames.Sensors))
            {
                propertyValidator = __CorvusValidateSensors;
                return true;
            }
        }

        propertyValidator = null;
        return false;
    }
}