//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Collections.Immutable;
using System.Text.Json;
using Corvus.Json;
using Corvus.Json.Internal;

namespace BuildingOS.Shared.Entities;
public readonly partial struct EnvironmentalDeviceMessageJson
{
    /// <summary>
    /// A type generated from a JsonSchema specification.
    /// </summary>
    public readonly partial struct EnvironmentalDeviceTelemetryEntity
    {
        /// <summary>
        /// Conversion to <see cref = "BuildingOS.Shared.Entities.EnvironmentalDeviceMessageJson.EnvironmentalDeviceTelemetryEntity.OneOf0Entity"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static explicit operator BuildingOS.Shared.Entities.EnvironmentalDeviceMessageJson.EnvironmentalDeviceTelemetryEntity.OneOf0Entity(EnvironmentalDeviceTelemetryEntity value)
        {
            if ((value.backing & Backing.JsonElement) != 0)
            {
                return new(value.AsJsonElement);
            }

            if ((value.backing & Backing.Object) != 0)
            {
                return new(value.objectBacking);
            }

            return BuildingOS.Shared.Entities.EnvironmentalDeviceMessageJson.EnvironmentalDeviceTelemetryEntity.OneOf0Entity.Undefined;
        }

        /// <summary>
        /// Conversion from <see cref = "BuildingOS.Shared.Entities.EnvironmentalDeviceMessageJson.EnvironmentalDeviceTelemetryEntity.OneOf0Entity"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static implicit operator EnvironmentalDeviceTelemetryEntity(BuildingOS.Shared.Entities.EnvironmentalDeviceMessageJson.EnvironmentalDeviceTelemetryEntity.OneOf0Entity value)
        {
            if (value.HasJsonElementBacking)
            {
                return new(value.AsJsonElement);
            }

            return value.ValueKind switch
            {
                JsonValueKind.Object => new(value.AsPropertyBacking()),
                _ => Undefined
            };
        }

        /// <summary>
        /// Conversion to <see cref = "BuildingOS.Shared.Entities.EnvironmentalDeviceMessageJson.EnvironmentalDeviceTelemetryEntity.OneOf1Entity"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static explicit operator BuildingOS.Shared.Entities.EnvironmentalDeviceMessageJson.EnvironmentalDeviceTelemetryEntity.OneOf1Entity(EnvironmentalDeviceTelemetryEntity value)
        {
            if ((value.backing & Backing.JsonElement) != 0)
            {
                return new(value.AsJsonElement);
            }

            if ((value.backing & Backing.Object) != 0)
            {
                return new(value.objectBacking);
            }

            return BuildingOS.Shared.Entities.EnvironmentalDeviceMessageJson.EnvironmentalDeviceTelemetryEntity.OneOf1Entity.Undefined;
        }

        /// <summary>
        /// Conversion from <see cref = "BuildingOS.Shared.Entities.EnvironmentalDeviceMessageJson.EnvironmentalDeviceTelemetryEntity.OneOf1Entity"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static implicit operator EnvironmentalDeviceTelemetryEntity(BuildingOS.Shared.Entities.EnvironmentalDeviceMessageJson.EnvironmentalDeviceTelemetryEntity.OneOf1Entity value)
        {
            if (value.HasJsonElementBacking)
            {
                return new(value.AsJsonElement);
            }

            return value.ValueKind switch
            {
                JsonValueKind.Object => new(value.AsPropertyBacking()),
                _ => Undefined
            };
        }
    }
}