//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Text.Json;
using Corvus.Json;
using Corvus.Json.Internal;

namespace BuildingOS.Shared.Entities;
public readonly partial struct HvacDeviceMessageJson
{
    /// <summary>
    /// A type generated from a JsonSchema specification.
    /// </summary>
    public readonly partial struct HvacDeviceTelemetryEntity
    {
        /// <summary>
        /// The well-known property names in the JSON object.
        /// </summary>
        public static class JsonPropertyNames
        {
            /// <summary>
            /// JSON property name for <see cref = "AmbientTemp"/>.
            /// </summary>
            public static ReadOnlySpan<byte> AmbientTempUtf8 => "ambientTemp"u8;

            /// <summary>
            /// JSON property name for <see cref = "AmbientTemp"/>.
            /// </summary>
            public const string AmbientTemp = "ambientTemp";
            /// <summary>
            /// JSON property name for <see cref = "Fan"/>.
            /// </summary>
            public static ReadOnlySpan<byte> FanUtf8 => "fan"u8;

            /// <summary>
            /// JSON property name for <see cref = "Fan"/>.
            /// </summary>
            public const string Fan = "fan";
            /// <summary>
            /// JSON property name for <see cref = "FilterSign"/>.
            /// </summary>
            public static ReadOnlySpan<byte> FilterSignUtf8 => "filterSign"u8;

            /// <summary>
            /// JSON property name for <see cref = "FilterSign"/>.
            /// </summary>
            public const string FilterSign = "filterSign";
            /// <summary>
            /// JSON property name for <see cref = "Mode"/>.
            /// </summary>
            public static ReadOnlySpan<byte> ModeUtf8 => "mode"u8;

            /// <summary>
            /// JSON property name for <see cref = "Mode"/>.
            /// </summary>
            public const string Mode = "mode";
            /// <summary>
            /// JSON property name for <see cref = "OnOff"/>.
            /// </summary>
            public static ReadOnlySpan<byte> OnOffUtf8 => "onOff"u8;

            /// <summary>
            /// JSON property name for <see cref = "OnOff"/>.
            /// </summary>
            public const string OnOff = "onOff";
            /// <summary>
            /// JSON property name for <see cref = "SetTemp"/>.
            /// </summary>
            public static ReadOnlySpan<byte> SetTempUtf8 => "setTemp"u8;

            /// <summary>
            /// JSON property name for <see cref = "SetTemp"/>.
            /// </summary>
            public const string SetTemp = "setTemp";
            /// <summary>
            /// JSON property name for <see cref = "Swing"/>.
            /// </summary>
            public static ReadOnlySpan<byte> SwingUtf8 => "swing"u8;

            /// <summary>
            /// JSON property name for <see cref = "Swing"/>.
            /// </summary>
            public const string Swing = "swing";
            /// <summary>
            /// JSON property name for <see cref = "UnitId"/>.
            /// </summary>
            public static ReadOnlySpan<byte> UnitIdUtf8 => "unitId"u8;

            /// <summary>
            /// JSON property name for <see cref = "UnitId"/>.
            /// </summary>
            public const string UnitId = "unitId";
            /// <summary>
            /// JSON property name for <see cref = "UnitName"/>.
            /// </summary>
            public static ReadOnlySpan<byte> UnitNameUtf8 => "unitName"u8;

            /// <summary>
            /// JSON property name for <see cref = "UnitName"/>.
            /// </summary>
            public const string UnitName = "unitName";
        }

        /// <summary>
        /// Gets AmbientTemp.
        /// </summary>
        public Corvus.Json.JsonNumber AmbientTemp
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.AmbientTempUtf8, out JsonElement result))
                    {
                        return new Corvus.Json.JsonNumber(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.AmbientTemp, out JsonAny result))
                    {
                        return result.As<Corvus.Json.JsonNumber>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets Fan.
        /// </summary>
        public Corvus.Json.JsonString Fan
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.FanUtf8, out JsonElement result))
                    {
                        return new Corvus.Json.JsonString(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.Fan, out JsonAny result))
                    {
                        return result.As<Corvus.Json.JsonString>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets FilterSign.
        /// </summary>
        public Corvus.Json.JsonNumber FilterSign
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.FilterSignUtf8, out JsonElement result))
                    {
                        return new Corvus.Json.JsonNumber(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.FilterSign, out JsonAny result))
                    {
                        return result.As<Corvus.Json.JsonNumber>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets Mode.
        /// </summary>
        public Corvus.Json.JsonString Mode
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.ModeUtf8, out JsonElement result))
                    {
                        return new Corvus.Json.JsonString(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.Mode, out JsonAny result))
                    {
                        return result.As<Corvus.Json.JsonString>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets OnOff.
        /// </summary>
        public Corvus.Json.JsonString OnOff
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.OnOffUtf8, out JsonElement result))
                    {
                        return new Corvus.Json.JsonString(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.OnOff, out JsonAny result))
                    {
                        return result.As<Corvus.Json.JsonString>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets SetTemp.
        /// </summary>
        public Corvus.Json.JsonNumber SetTemp
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.SetTempUtf8, out JsonElement result))
                    {
                        return new Corvus.Json.JsonNumber(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.SetTemp, out JsonAny result))
                    {
                        return result.As<Corvus.Json.JsonNumber>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets Swing.
        /// </summary>
        public Corvus.Json.JsonString Swing
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.SwingUtf8, out JsonElement result))
                    {
                        return new Corvus.Json.JsonString(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.Swing, out JsonAny result))
                    {
                        return result.As<Corvus.Json.JsonString>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets UnitId.
        /// </summary>
        public BuildingOS.Shared.Entities.HvacDeviceMessageJson.HvacDeviceTelemetryEntity.UnitIdEntity UnitId
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.UnitIdUtf8, out JsonElement result))
                    {
                        return new BuildingOS.Shared.Entities.HvacDeviceMessageJson.HvacDeviceTelemetryEntity.UnitIdEntity(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.UnitId, out JsonAny result))
                    {
                        return result.As<BuildingOS.Shared.Entities.HvacDeviceMessageJson.HvacDeviceTelemetryEntity.UnitIdEntity>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets UnitName.
        /// </summary>
        public Corvus.Json.JsonString UnitName
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.UnitNameUtf8, out JsonElement result))
                    {
                        return new Corvus.Json.JsonString(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.UnitName, out JsonAny result))
                    {
                        return result.As<Corvus.Json.JsonString>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Creates an instance of a <see cref = "HvacDeviceTelemetryEntity"/>.
        /// </summary>
        public static HvacDeviceTelemetryEntity Create(Corvus.Json.JsonNumber ambientTemp, BuildingOS.Shared.Entities.HvacDeviceMessageJson.HvacDeviceTelemetryEntity.UnitIdEntity unitId, Corvus.Json.JsonString unitName, Corvus.Json.JsonString? fan = null, Corvus.Json.JsonNumber? filterSign = null, Corvus.Json.JsonString? mode = null, Corvus.Json.JsonString? onOff = null, Corvus.Json.JsonNumber? setTemp = null, Corvus.Json.JsonString? swing = null)
        {
            var builder = ImmutableList.CreateBuilder<JsonObjectProperty>();
            builder.Add(JsonPropertyNames.AmbientTemp, ambientTemp.AsAny);
            builder.Add(JsonPropertyNames.UnitId, unitId.AsAny);
            builder.Add(JsonPropertyNames.UnitName, unitName.AsAny);
            if (fan is Corvus.Json.JsonString fan__)
            {
                builder.Add(JsonPropertyNames.Fan, fan__.AsAny);
            }

            if (filterSign is Corvus.Json.JsonNumber filterSign__)
            {
                builder.Add(JsonPropertyNames.FilterSign, filterSign__.AsAny);
            }

            if (mode is Corvus.Json.JsonString mode__)
            {
                builder.Add(JsonPropertyNames.Mode, mode__.AsAny);
            }

            if (onOff is Corvus.Json.JsonString onOff__)
            {
                builder.Add(JsonPropertyNames.OnOff, onOff__.AsAny);
            }

            if (setTemp is Corvus.Json.JsonNumber setTemp__)
            {
                builder.Add(JsonPropertyNames.SetTemp, setTemp__.AsAny);
            }

            if (swing is Corvus.Json.JsonString swing__)
            {
                builder.Add(JsonPropertyNames.Swing, swing__.AsAny);
            }

            return new(builder.ToImmutable());
        }

        /// <summary>
        /// Sets ambientTemp.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public HvacDeviceTelemetryEntity WithAmbientTemp(in Corvus.Json.JsonNumber value)
        {
            return this.SetProperty(JsonPropertyNames.AmbientTemp, value);
        }

        /// <summary>
        /// Sets fan.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public HvacDeviceTelemetryEntity WithFan(in Corvus.Json.JsonString value)
        {
            return this.SetProperty(JsonPropertyNames.Fan, value);
        }

        /// <summary>
        /// Sets filterSign.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public HvacDeviceTelemetryEntity WithFilterSign(in Corvus.Json.JsonNumber value)
        {
            return this.SetProperty(JsonPropertyNames.FilterSign, value);
        }

        /// <summary>
        /// Sets mode.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public HvacDeviceTelemetryEntity WithMode(in Corvus.Json.JsonString value)
        {
            return this.SetProperty(JsonPropertyNames.Mode, value);
        }

        /// <summary>
        /// Sets onOff.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public HvacDeviceTelemetryEntity WithOnOff(in Corvus.Json.JsonString value)
        {
            return this.SetProperty(JsonPropertyNames.OnOff, value);
        }

        /// <summary>
        /// Sets setTemp.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public HvacDeviceTelemetryEntity WithSetTemp(in Corvus.Json.JsonNumber value)
        {
            return this.SetProperty(JsonPropertyNames.SetTemp, value);
        }

        /// <summary>
        /// Sets swing.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public HvacDeviceTelemetryEntity WithSwing(in Corvus.Json.JsonString value)
        {
            return this.SetProperty(JsonPropertyNames.Swing, value);
        }

        /// <summary>
        /// Sets unitId.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public HvacDeviceTelemetryEntity WithUnitId(in BuildingOS.Shared.Entities.HvacDeviceMessageJson.HvacDeviceTelemetryEntity.UnitIdEntity value)
        {
            return this.SetProperty(JsonPropertyNames.UnitId, value);
        }

        /// <summary>
        /// Sets unitName.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public HvacDeviceTelemetryEntity WithUnitName(in Corvus.Json.JsonString value)
        {
            return this.SetProperty(JsonPropertyNames.UnitName, value);
        }

        private static ValidationContext __CorvusValidateUnitId(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<BuildingOS.Shared.Entities.HvacDeviceMessageJson.HvacDeviceTelemetryEntity.UnitIdEntity>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateUnitName(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Corvus.Json.JsonString>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateAmbientTemp(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Corvus.Json.JsonNumber>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateMode(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Corvus.Json.JsonString>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateFan(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Corvus.Json.JsonString>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateSetTemp(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Corvus.Json.JsonNumber>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateOnOff(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Corvus.Json.JsonString>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateFilterSign(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Corvus.Json.JsonNumber>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateSwing(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Corvus.Json.JsonString>().Validate(validationContext, level);
        }

        /// <summary>
        /// Tries to get the validator for the given property.
        /// </summary>
        /// <param name = "property">The property for which to get the validator.</param>
        /// <param name = "hasJsonElementBacking"><c>True</c> if the object containing the property has a JsonElement backing.</param>
        /// <param name = "propertyValidator">The validator for the property, if provided by this schema.</param>
        /// <returns><c>True</c> if the validator was found.</returns>
        private bool __TryGetCorvusLocalPropertiesValidator(in JsonObjectProperty property, bool hasJsonElementBacking, [NotNullWhen(true)] out ObjectPropertyValidator? propertyValidator)
        {
            if (hasJsonElementBacking)
            {
                if (property.NameEquals(JsonPropertyNames.UnitIdUtf8))
                {
                    propertyValidator = __CorvusValidateUnitId;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.UnitNameUtf8))
                {
                    propertyValidator = __CorvusValidateUnitName;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.AmbientTempUtf8))
                {
                    propertyValidator = __CorvusValidateAmbientTemp;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.ModeUtf8))
                {
                    propertyValidator = __CorvusValidateMode;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.FanUtf8))
                {
                    propertyValidator = __CorvusValidateFan;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.SetTempUtf8))
                {
                    propertyValidator = __CorvusValidateSetTemp;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.OnOffUtf8))
                {
                    propertyValidator = __CorvusValidateOnOff;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.FilterSignUtf8))
                {
                    propertyValidator = __CorvusValidateFilterSign;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.SwingUtf8))
                {
                    propertyValidator = __CorvusValidateSwing;
                    return true;
                }
            }
            else
            {
                if (property.NameEquals(JsonPropertyNames.UnitId))
                {
                    propertyValidator = __CorvusValidateUnitId;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.UnitName))
                {
                    propertyValidator = __CorvusValidateUnitName;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.AmbientTemp))
                {
                    propertyValidator = __CorvusValidateAmbientTemp;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.Mode))
                {
                    propertyValidator = __CorvusValidateMode;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.Fan))
                {
                    propertyValidator = __CorvusValidateFan;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.SetTemp))
                {
                    propertyValidator = __CorvusValidateSetTemp;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.OnOff))
                {
                    propertyValidator = __CorvusValidateOnOff;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.FilterSign))
                {
                    propertyValidator = __CorvusValidateFilterSign;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.Swing))
                {
                    propertyValidator = __CorvusValidateSwing;
                    return true;
                }
            }

            propertyValidator = null;
            return false;
        }
    }
}