//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Text.Json;
using Corvus.Json;

namespace BuildingOS.Shared.Entities;
public readonly partial struct ValidMessage
{
    public readonly partial struct ValidTelemetryEntity
    {
        /// <summary>
        /// Generated from JSON Schema.
        /// </summary>
        /// <remarks>
        /// <para>
        /// Representative value of the telemetry data. Numeric is the primary type (charts/aggregation); string and boolean are first-class state/status values (#152). The discriminant is carried alongside as value_type in the persistence/API layers; numeric stays fully backward-compatible.
        /// </para>
        /// </remarks>
        public readonly partial struct ValueEntity
        {
            /// <inheritdoc/>
            public ValidationContext Validate(in ValidationContext validationContext, ValidationLevel level = ValidationLevel.Flag)
            {
                ValidationContext result = validationContext;
                if (level > ValidationLevel.Flag)
                {
                    result = result.UsingResults();
                }

                if (level > ValidationLevel.Basic)
                {
                    result = result.UsingStack();
                    result = result.PushSchemaLocation("https://endjin.com/home/user/gutp-building-os-ri/DotNet/BuildingOS.Shared/Defines/Schemas/valid-message.json#/$defs/validTelemetry/properties/value");
                }

                JsonValueKind valueKind = this.ValueKind;
                result = this.ValidateType(valueKind, result, level);
                if (level == ValidationLevel.Flag && !result.IsValid)
                {
                    return result;
                }

                if (level != ValidationLevel.Flag)
                {
                    result = result.PopLocation();
                }

                return result;
            }
        }
    }
}