//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Text.Json;
using Corvus.Json;
using Corvus.Json.Internal;

namespace BuildingOS.Shared.Entities;
public readonly partial struct ValidMessage
{
    /// <summary>
    /// Validated Telemetry
    /// </summary>
    /// <remarks>
    /// <para>
    /// Schema for validated telemetry data from Building devices
    /// </para>
    /// </remarks>
    public readonly partial struct ValidTelemetryEntity
    {
        /// <summary>
        /// The well-known property names in the JSON object.
        /// </summary>
        public static class JsonPropertyNames
        {
            /// <summary>
            /// JSON property name for <see cref = "Building"/>.
            /// </summary>
            public static ReadOnlySpan<byte> BuildingUtf8 => "building"u8;

            /// <summary>
            /// JSON property name for <see cref = "Building"/>.
            /// </summary>
            public const string Building = "building";
            /// <summary>
            /// JSON property name for <see cref = "Data"/>.
            /// </summary>
            public static ReadOnlySpan<byte> DataUtf8 => "data"u8;

            /// <summary>
            /// JSON property name for <see cref = "Data"/>.
            /// </summary>
            public const string Data = "data";
            /// <summary>
            /// JSON property name for <see cref = "Datetime"/>.
            /// </summary>
            public static ReadOnlySpan<byte> DatetimeUtf8 => "datetime"u8;

            /// <summary>
            /// JSON property name for <see cref = "Datetime"/>.
            /// </summary>
            public const string Datetime = "datetime";
            /// <summary>
            /// JSON property name for <see cref = "DeviceId"/>.
            /// </summary>
            public static ReadOnlySpan<byte> DeviceIdUtf8 => "device_id"u8;

            /// <summary>
            /// JSON property name for <see cref = "DeviceId"/>.
            /// </summary>
            public const string DeviceId = "device_id";
            /// <summary>
            /// JSON property name for <see cref = "Id"/>.
            /// </summary>
            public static ReadOnlySpan<byte> IdUtf8 => "id"u8;

            /// <summary>
            /// JSON property name for <see cref = "Id"/>.
            /// </summary>
            public const string Id = "id";
            /// <summary>
            /// JSON property name for <see cref = "Name"/>.
            /// </summary>
            public static ReadOnlySpan<byte> NameUtf8 => "name"u8;

            /// <summary>
            /// JSON property name for <see cref = "Name"/>.
            /// </summary>
            public const string Name = "name";
            /// <summary>
            /// JSON property name for <see cref = "PointId"/>.
            /// </summary>
            public static ReadOnlySpan<byte> PointIdUtf8 => "point_id"u8;

            /// <summary>
            /// JSON property name for <see cref = "PointId"/>.
            /// </summary>
            public const string PointId = "point_id";
            /// <summary>
            /// JSON property name for <see cref = "Value"/>.
            /// </summary>
            public static ReadOnlySpan<byte> ValueUtf8 => "value"u8;

            /// <summary>
            /// JSON property name for <see cref = "Value"/>.
            /// </summary>
            public const string Value = "value";
        }

        /// <summary>
        /// Gets the <c>building</c> property. If the instance is valid, this property will be not be <c>undefined</c>.
        /// </summary>
        /// <remarks>
        /// <para>
        /// Name of the building the telemetry point belongs to
        /// </para>
        /// </remarks>
        public Corvus.Json.JsonString Building
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.BuildingUtf8, out JsonElement result))
                    {
                        return new Corvus.Json.JsonString(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.Building, out JsonAny result))
                    {
                        return result.As<Corvus.Json.JsonString>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets the <c>data</c> property. If the instance is valid, this property will be not be <c>undefined</c>.
        /// </summary>
        /// <remarks>
        /// <para>
        /// Additional data associated with the telemetry point
        /// </para>
        /// </remarks>
        public BuildingOS.Shared.Entities.ValidMessage.ValidTelemetryEntity.DataEntity Data
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.DataUtf8, out JsonElement result))
                    {
                        return new BuildingOS.Shared.Entities.ValidMessage.ValidTelemetryEntity.DataEntity(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.Data, out JsonAny result))
                    {
                        return result.As<BuildingOS.Shared.Entities.ValidMessage.ValidTelemetryEntity.DataEntity>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets the <c>datetime</c> property. If the instance is valid, this property will be not be <c>undefined</c>.
        /// </summary>
        /// <remarks>
        /// <para>
        /// Date and time when the telemetry data was recorded in ISO 8601 format
        /// </para>
        /// </remarks>
        public Corvus.Json.JsonDateTime Datetime
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.DatetimeUtf8, out JsonElement result))
                    {
                        return new Corvus.Json.JsonDateTime(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.Datetime, out JsonAny result))
                    {
                        return result.As<Corvus.Json.JsonDateTime>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets the <c>device_id</c> property. If the instance is valid, this property will be not be <c>undefined</c>.
        /// </summary>
        /// <remarks>
        /// <para>
        /// identifier for the device
        /// </para>
        /// </remarks>
        public Corvus.Json.JsonString DeviceId
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.DeviceIdUtf8, out JsonElement result))
                    {
                        return new Corvus.Json.JsonString(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.DeviceId, out JsonAny result))
                    {
                        return result.As<Corvus.Json.JsonString>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets the (optional) <c>id</c> property.
        /// </summary>
        /// <remarks>
        /// <para>
        /// Unique identifier for the message
        /// </para>
        /// </remarks>
        public Corvus.Json.JsonString Id
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.IdUtf8, out JsonElement result))
                    {
                        return new Corvus.Json.JsonString(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.Id, out JsonAny result))
                    {
                        return result.As<Corvus.Json.JsonString>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets the (optional) <c>name</c> property.
        /// </summary>
        /// <remarks>
        /// <para>
        /// Optional name of the telemetry point
        /// </para>
        /// </remarks>
        public Corvus.Json.JsonString Name
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.NameUtf8, out JsonElement result))
                    {
                        return new Corvus.Json.JsonString(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.Name, out JsonAny result))
                    {
                        return result.As<Corvus.Json.JsonString>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets the <c>point_id</c> property. If the instance is valid, this property will be not be <c>undefined</c>.
        /// </summary>
        /// <remarks>
        /// <para>
        /// Unique identifier for the telemetry point
        /// </para>
        /// </remarks>
        public Corvus.Json.JsonString PointId
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.PointIdUtf8, out JsonElement result))
                    {
                        return new Corvus.Json.JsonString(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.PointId, out JsonAny result))
                    {
                        return result.As<Corvus.Json.JsonString>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets the <c>value</c> property. If the instance is valid, this property will be not be <c>undefined</c>.
        /// </summary>
        /// <remarks>
        /// <para>
        /// Representative value of the telemetry data
        /// </para>
        /// </remarks>
        public Corvus.Json.JsonNumber Value
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.ValueUtf8, out JsonElement result))
                    {
                        return new Corvus.Json.JsonNumber(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.Value, out JsonAny result))
                    {
                        return result.As<Corvus.Json.JsonNumber>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Creates an instance of a <see cref = "ValidTelemetryEntity"/>.
        /// </summary>
        public static ValidTelemetryEntity Create(Corvus.Json.JsonString building, BuildingOS.Shared.Entities.ValidMessage.ValidTelemetryEntity.DataEntity data, Corvus.Json.JsonDateTime datetime, Corvus.Json.JsonString deviceId, Corvus.Json.JsonString pointId, Corvus.Json.JsonNumber value, Corvus.Json.JsonString? id = null, Corvus.Json.JsonString? name = null)
        {
            var builder = ImmutableList.CreateBuilder<JsonObjectProperty>();
            builder.Add(JsonPropertyNames.Building, building.AsAny);
            builder.Add(JsonPropertyNames.Data, data.AsAny);
            builder.Add(JsonPropertyNames.Datetime, datetime.AsAny);
            builder.Add(JsonPropertyNames.DeviceId, deviceId.AsAny);
            builder.Add(JsonPropertyNames.PointId, pointId.AsAny);
            builder.Add(JsonPropertyNames.Value, value.AsAny);
            if (id is Corvus.Json.JsonString id__)
            {
                builder.Add(JsonPropertyNames.Id, id__.AsAny);
            }

            if (name is Corvus.Json.JsonString name__)
            {
                builder.Add(JsonPropertyNames.Name, name__.AsAny);
            }

            return new(builder.ToImmutable());
        }

        /// <summary>
        /// Sets building.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public ValidTelemetryEntity WithBuilding(in Corvus.Json.JsonString value)
        {
            return this.SetProperty(JsonPropertyNames.Building, value);
        }

        /// <summary>
        /// Sets data.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public ValidTelemetryEntity WithData(in BuildingOS.Shared.Entities.ValidMessage.ValidTelemetryEntity.DataEntity value)
        {
            return this.SetProperty(JsonPropertyNames.Data, value);
        }

        /// <summary>
        /// Sets datetime.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public ValidTelemetryEntity WithDatetime(in Corvus.Json.JsonDateTime value)
        {
            return this.SetProperty(JsonPropertyNames.Datetime, value);
        }

        /// <summary>
        /// Sets device_id.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public ValidTelemetryEntity WithDeviceId(in Corvus.Json.JsonString value)
        {
            return this.SetProperty(JsonPropertyNames.DeviceId, value);
        }

        /// <summary>
        /// Sets id.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public ValidTelemetryEntity WithId(in Corvus.Json.JsonString value)
        {
            return this.SetProperty(JsonPropertyNames.Id, value);
        }

        /// <summary>
        /// Sets name.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public ValidTelemetryEntity WithName(in Corvus.Json.JsonString value)
        {
            return this.SetProperty(JsonPropertyNames.Name, value);
        }

        /// <summary>
        /// Sets point_id.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public ValidTelemetryEntity WithPointId(in Corvus.Json.JsonString value)
        {
            return this.SetProperty(JsonPropertyNames.PointId, value);
        }

        /// <summary>
        /// Sets value.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public ValidTelemetryEntity WithValue(in Corvus.Json.JsonNumber value)
        {
            return this.SetProperty(JsonPropertyNames.Value, value);
        }

        private static ValidationContext __CorvusValidateDeviceId(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Corvus.Json.JsonString>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidatePointId(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Corvus.Json.JsonString>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateBuilding(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Corvus.Json.JsonString>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateValue(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Corvus.Json.JsonNumber>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateData(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<BuildingOS.Shared.Entities.ValidMessage.ValidTelemetryEntity.DataEntity>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateDatetime(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Corvus.Json.JsonDateTime>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateId(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Corvus.Json.JsonString>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateName(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Corvus.Json.JsonString>().Validate(validationContext, level);
        }

        /// <summary>
        /// Tries to get the validator for the given property.
        /// </summary>
        /// <param name = "property">The property for which to get the validator.</param>
        /// <param name = "hasJsonElementBacking"><c>True</c> if the object containing the property has a JsonElement backing.</param>
        /// <param name = "propertyValidator">The validator for the property, if provided by this schema.</param>
        /// <returns><c>True</c> if the validator was found.</returns>
        private bool __TryGetCorvusLocalPropertiesValidator(in JsonObjectProperty property, bool hasJsonElementBacking, [NotNullWhen(true)] out ObjectPropertyValidator? propertyValidator)
        {
            if (hasJsonElementBacking)
            {
                if (property.NameEquals(JsonPropertyNames.DeviceIdUtf8))
                {
                    propertyValidator = __CorvusValidateDeviceId;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.PointIdUtf8))
                {
                    propertyValidator = __CorvusValidatePointId;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.BuildingUtf8))
                {
                    propertyValidator = __CorvusValidateBuilding;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.ValueUtf8))
                {
                    propertyValidator = __CorvusValidateValue;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.DataUtf8))
                {
                    propertyValidator = __CorvusValidateData;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.DatetimeUtf8))
                {
                    propertyValidator = __CorvusValidateDatetime;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.IdUtf8))
                {
                    propertyValidator = __CorvusValidateId;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.NameUtf8))
                {
                    propertyValidator = __CorvusValidateName;
                    return true;
                }
            }
            else
            {
                if (property.NameEquals(JsonPropertyNames.DeviceId))
                {
                    propertyValidator = __CorvusValidateDeviceId;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.PointId))
                {
                    propertyValidator = __CorvusValidatePointId;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.Building))
                {
                    propertyValidator = __CorvusValidateBuilding;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.Value))
                {
                    propertyValidator = __CorvusValidateValue;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.Data))
                {
                    propertyValidator = __CorvusValidateData;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.Datetime))
                {
                    propertyValidator = __CorvusValidateDatetime;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.Id))
                {
                    propertyValidator = __CorvusValidateId;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.Name))
                {
                    propertyValidator = __CorvusValidateName;
                    return true;
                }
            }

            propertyValidator = null;
            return false;
        }
    }
}