//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Text.Json;
using Corvus.Json;

namespace BuildingOS.Shared.Entities;
public readonly partial struct ValidMessage
{
    public readonly partial struct ValidTelemetryEntity
    {
        /// <summary>
        /// Generated from JSON Schema.
        /// </summary>
        /// <remarks>
        /// <para>
        /// Representative value of the telemetry data. Numeric is the primary type (charts/aggregation); string and boolean are first-class state/status values (#152). The discriminant is carried alongside as value_type in the persistence/API layers; numeric stays fully backward-compatible.
        /// </para>
        /// </remarks>
        public readonly partial struct ValueEntity
        {
            private ValidationContext ValidateType(JsonValueKind valueKind, in ValidationContext validationContext, ValidationLevel level)
            {
                ValidationContext result = validationContext;
                bool isValid = false;
                ValidationContext localResultString = Corvus.Json.Validate.TypeString(valueKind, result.CreateChildContext(), level);
                if (level == ValidationLevel.Flag && localResultString.IsValid)
                {
                    return validationContext;
                }

                if (localResultString.IsValid)
                {
                    isValid = true;
                }

                ValidationContext localResultNumber = Corvus.Json.Validate.TypeNumber(valueKind, result.CreateChildContext(), level);
                if (level == ValidationLevel.Flag && localResultNumber.IsValid)
                {
                    return validationContext;
                }

                if (localResultNumber.IsValid)
                {
                    isValid = true;
                }

                ValidationContext localResultBoolean = Corvus.Json.Validate.TypeBoolean(valueKind, result.CreateChildContext(), level);
                if (level == ValidationLevel.Flag && localResultBoolean.IsValid)
                {
                    return validationContext;
                }

                if (localResultBoolean.IsValid)
                {
                    isValid = true;
                }

                result = result.MergeResults(isValid, level, localResultString, localResultNumber, localResultBoolean);
                return result;
            }
        }
    }
}