//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Collections.Immutable;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using Corvus.Json;
using Corvus.Json.Internal;

namespace BuildingOS.Shared.Entities;
public readonly partial struct ValidMessage
{
    /// <summary>
    /// Validated Telemetry
    /// </summary>
    /// <remarks>
    /// <para>
    /// Schema for validated telemetry data from Building devices
    /// </para>
    /// </remarks>
    public readonly partial struct ValidTelemetryEntity
    {
        private ValidationContext ValidateObject(JsonValueKind valueKind, in ValidationContext validationContext, ValidationLevel level)
        {
            ValidationContext result = validationContext;
            if (valueKind != JsonValueKind.Object)
            {
                return result;
            }

            int propertyCount = 0;
            bool foundBuilding = false;
            bool foundData = false;
            bool foundDatetime = false;
            bool foundDeviceId = false;
            bool foundPointId = false;
            bool foundValue = false;
            foreach (JsonObjectProperty property in this.EnumerateObject())
            {
                if (__TryGetCorvusLocalPropertiesValidator(property, this.HasJsonElementBacking, out ObjectPropertyValidator? propertyValidator))
                {
                    result = result.WithLocalProperty(propertyCount);
                    if (level > ValidationLevel.Basic)
                    {
                        result = result.PushDocumentProperty("properties", property.Name.GetString());
                    }

                    var propertyResult = propertyValidator(property, result.CreateChildContext(), level);
                    result = result.MergeResults(propertyResult.IsValid, level, propertyResult);
                    if (level > ValidationLevel.Basic)
                    {
                        result = result.PopLocation(); // property name
                    }

                    if (level == ValidationLevel.Flag && !result.IsValid)
                    {
                        return result;
                    }

                    if ((this.HasJsonElementBacking && property.NameEquals(JsonPropertyNames.BuildingUtf8)) || (!this.HasJsonElementBacking && property.NameEquals(JsonPropertyNames.Building)))
                    {
                        foundBuilding = true;
                    }
                    else if ((this.HasJsonElementBacking && property.NameEquals(JsonPropertyNames.DataUtf8)) || (!this.HasJsonElementBacking && property.NameEquals(JsonPropertyNames.Data)))
                    {
                        foundData = true;
                    }
                    else if ((this.HasJsonElementBacking && property.NameEquals(JsonPropertyNames.DatetimeUtf8)) || (!this.HasJsonElementBacking && property.NameEquals(JsonPropertyNames.Datetime)))
                    {
                        foundDatetime = true;
                    }
                    else if ((this.HasJsonElementBacking && property.NameEquals(JsonPropertyNames.DeviceIdUtf8)) || (!this.HasJsonElementBacking && property.NameEquals(JsonPropertyNames.DeviceId)))
                    {
                        foundDeviceId = true;
                    }
                    else if ((this.HasJsonElementBacking && property.NameEquals(JsonPropertyNames.PointIdUtf8)) || (!this.HasJsonElementBacking && property.NameEquals(JsonPropertyNames.PointId)))
                    {
                        foundPointId = true;
                    }
                    else if ((this.HasJsonElementBacking && property.NameEquals(JsonPropertyNames.ValueUtf8)) || (!this.HasJsonElementBacking && property.NameEquals(JsonPropertyNames.Value)))
                    {
                        foundValue = true;
                    }
                }

                if (!result.HasEvaluatedLocalProperty(propertyCount))
                {
                    if (level >= ValidationLevel.Detailed)
                    {
                        result = result.WithResult(isValid: false, $"9.3.2.3. additionalProperties - additional property \"{property.Name}\" is not permitted.");
                    }
                    else if (level >= ValidationLevel.Basic)
                    {
                        result = result.WithResult(isValid: false, "9.3.2.3. additionalProperties - additional properties are not permitted.");
                    }
                    else
                    {
                        return result.WithResult(isValid: false);
                    }
                }

                propertyCount++;
            }

            if (!foundBuilding)
            {
                if (level >= ValidationLevel.Detailed)
                {
                    result = result.WithResult(isValid: false, $"6.5.3. required - required property \"building\" not present.");
                }
                else if (level >= ValidationLevel.Basic)
                {
                    result = result.WithResult(isValid: false, "6.5.3. required - required property not present.");
                }
                else
                {
                    return result.WithResult(isValid: false);
                }
            }

            if (!foundData)
            {
                if (level >= ValidationLevel.Detailed)
                {
                    result = result.WithResult(isValid: false, $"6.5.3. required - required property \"data\" not present.");
                }
                else if (level >= ValidationLevel.Basic)
                {
                    result = result.WithResult(isValid: false, "6.5.3. required - required property not present.");
                }
                else
                {
                    return result.WithResult(isValid: false);
                }
            }

            if (!foundDatetime)
            {
                if (level >= ValidationLevel.Detailed)
                {
                    result = result.WithResult(isValid: false, $"6.5.3. required - required property \"datetime\" not present.");
                }
                else if (level >= ValidationLevel.Basic)
                {
                    result = result.WithResult(isValid: false, "6.5.3. required - required property not present.");
                }
                else
                {
                    return result.WithResult(isValid: false);
                }
            }

            if (!foundDeviceId)
            {
                if (level >= ValidationLevel.Detailed)
                {
                    result = result.WithResult(isValid: false, $"6.5.3. required - required property \"device_id\" not present.");
                }
                else if (level >= ValidationLevel.Basic)
                {
                    result = result.WithResult(isValid: false, "6.5.3. required - required property not present.");
                }
                else
                {
                    return result.WithResult(isValid: false);
                }
            }

            if (!foundPointId)
            {
                if (level >= ValidationLevel.Detailed)
                {
                    result = result.WithResult(isValid: false, $"6.5.3. required - required property \"point_id\" not present.");
                }
                else if (level >= ValidationLevel.Basic)
                {
                    result = result.WithResult(isValid: false, "6.5.3. required - required property not present.");
                }
                else
                {
                    return result.WithResult(isValid: false);
                }
            }

            if (!foundValue)
            {
                if (level >= ValidationLevel.Detailed)
                {
                    result = result.WithResult(isValid: false, $"6.5.3. required - required property \"value\" not present.");
                }
                else if (level >= ValidationLevel.Basic)
                {
                    result = result.WithResult(isValid: false, "6.5.3. required - required property not present.");
                }
                else
                {
                    return result.WithResult(isValid: false);
                }
            }

            return result;
        }
    }
}