apiVersion: v2
name: building-os
description: Building OS - Smart Building IoT Platform (OSS stack)
type: application
version: 1.0.0-rc.2
appVersion: "1.0.0-rc.2"
keywords:
  - building-os
  - iot
  - nextjs
  - nats
  - timescaledb
maintainers:
  - name: Building OS Team
    email: team@building-os.example.com
